; multi-line context in Rampant Variables
(context/map-r17+ 
    (
        ("default" 0 (lambda () #t) (lambda () #f) #f) 
        ("update derivatives after flow-solve" 90 (lambda () (rpgetvar 'context/auto-detect?)) (lambda () #t) (mom/update-derivatives-after-flow-solve? #t boolean #f #t #t)) 
        ("turbulence models based on epsilon are first-order in space" 95 
            (lambda () (let* ((rpconf (%rp-config #f)) (sgmphs (cdr (assq 'sg-mphase? rpconf)))) (or (eq? sgmphs 'multi-fluid) (eq? sgmphs 'drift-flux) (eq? sgmphs 'homogeneous) (cdr (assq 'rp-ke? rpconf)) (cdr (assq 'rp-v2f? rpconf)) (and (cdr (assq 'rp-des? rpconf)) (rpgetvar 'des-rke-on?)) (and (cdr (assq 'sg-rsm? rpconf)) (not (drsm-omega-or-bsl-based?)) (rpgetvar 'drsm-tke-solve?))))) 
            (lambda () #t) 
            (k/scheme 0 integer #f 0 1 ("Changing Discretization Scheme for Turbulent Kinetic Energy:   ~a" (
                ("First Order Upwind" . 0) 
                ("Second Order Upwind" . 1) 
                ("Power Law" . 2) 
                ("Central Differencing" . 3) 
                ("QUICK" . 4) 
                ("Modified HRIC" . 5) 
                ("Third-Order MUSCL" . 6) 
                ("Bounded Central Differencing" . 7) 
                ("CICSAM" . 8) 
                ("Low Diffusion Second Order" . 9) 
                ("Standard" . 10) 
                ("Linear" . 11) 
                ("Second Order" . 12) 
                ("Body Force Weighted" . 13) 
                ("PRESTO!" . 14) 
                ("Continuity Based" . 15) 
                ("Geo-Reconstruct" . 16) 
                ("Donor-Acceptor" . 17) 
                ("Modified Body Force Weighted" . 18) 
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Coupled" . 24) 
                ("Fractional Step" . 25) 
                ("Compressive" . 28) 
                ("BGM" . 29) 
                ("Phase Coupled PISO" . 30) 
                ("Low Diffusion Central" . 31)
            )))
        ) 
        ("RSM omega-based turbulence models are first-order in space" 97 
            (lambda () (let* ((rpconf (%rp-config #f)) (sgmphs (cdr (assq 'sg-mphase? rpconf)))) (or (eq? sgmphs 'multi-fluid) (eq? sgmphs 'drift-flux) (eq? sgmphs 'homogeneous) (and (cdr (assq 'sg-rsm? rpconf)) (drsm-omega-or-bsl-based?))))) 
            (lambda () #t) 
            (omega/scheme 0 integer #f 0 1 ("Changing Discretization Scheme for Specific Dissipation Rate:  ~a" (
                ("First Order Upwind" . 0) 
                ("Second Order Upwind" . 1) 
                ("Power Law" . 2) 
                ("Central Differencing" . 3) 
                ("QUICK" . 4) 
                ("Modified HRIC" . 5) 
                ("Third-Order MUSCL" . 6) 
                ("Bounded Central Differencing" . 7) 
                ("CICSAM" . 8) 
                ("Low Diffusion Second Order" . 9) 
                ("Standard" . 10) 
                ("Linear" . 11) 
                ("Second Order" . 12) 
                ("Body Force Weighted" . 13) 
                ("PRESTO!" . 14) 
                ("Continuity Based" . 15) 
                ("Geo-Reconstruct" . 16) 
                ("Donor-Acceptor" . 17) 
                ("Modified Body Force Weighted" . 18) 
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Coupled" . 24) 
                ("Fractional Step" . 25) 
                ("Compressive" . 28) 
                ("BGM" . 29) 
                ("Phase Coupled PISO" . 30) 
                ("Low Diffusion Central" . 31)
                )))
        ) 
        ("pseudo-transient IF (single-phase) PBNS steady" 100 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (not (cdr (assq 'rp-unsteady? (%rp-config #f)))))) 
            (lambda () #t) 
            (pseudo-transient-formulation? #t boolean #f #t #f ("Pseudo transient formulation:                    ~a" (("enabled" . #t) ("disabled" . #f))))
        ) 
        ("NOT pseudo-transient IF (single-phase) transient" 120 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (cdr (assq 'rp-unsteady? (%rp-config #f))))) 
            (lambda () #t) 
            (pseudo-transient-formulation? #f boolean #f #f #f ("Pseudo transient formulation:                    ~a" (("enabled" . #t) ("disabled" . #f))))
        ) 
        ("compr. enh. num. + press.-cpld. F cycle IF (single-phase) PBNS" 130 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))))) 
            (lambda () #t) 
            (compress/enhanced-numerics/on? #t boolean #f #t #t) (pressure-coupled/cycle-type 3 integer #f 3 3 ("Multigrid cycle type for the pressure coupled:   ~a" ((0 . "Flexible") (1 . "V-Cycle") (2 . "W-Cycle") (3 . "F-Cycle"))))
        ) 
        ("HOTR IF (single-phase) except PBNS Transient" 140 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (not (and (cdr (assq 'rp-seg? (%rp-config #f))) (cdr (assq 'rp-unsteady? (%rp-config #f))))))) 
            (lambda () #t) 
            (recon/relax/relax? #t boolean #f #t #f ("HOTR:                                            ~a" (("enabled" . #t) ("disabled" . #f))))
        ) 
        ("coupled IF (single-phase) PBNS steady" 150 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (gpuapp-gui-enabled?)) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (not (cdr (assq 'rp-unsteady? (%rp-config #f)))))) 
            (lambda () #t) 
            (density/relax 0.5 real #f 0.5 1 ("Under-Relaxation Factor for density              ~a")) 
            (density/pseudo-relax 0.5 real #f 0.5 1.) 
            (flow/scheme 24 integer #f 24 20 ("P-V coupling method:                             ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            )))
        ) 
        ("simpleC IF (single-phase) PBNS transient" 170 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (cdr (assq 'rp-unsteady? (%rp-config #f))))) 
            (lambda () #t) 
            (pressure/relax 0.8 real #f 0.8 0.3 ("Under-Relaxation Factor for pressure:            ~a")) 
            (mom/relax 0.7 real #f 0.7 0.7 ("Under-Relaxation Factor for momentum:            ~a")) 
            (simplec/skew-iter 1 integer #f 1 0 ("Skewness Correction for SIMPLEC                  ~a")) 
            (density/relax 1 real #f 1 1 ("Under-Relaxation Factor for density              ~a")) 
            (density/pseudo-relax 1 real #f 1 1.) 
            (pressure-coupled/courant-number 10000000000. real #f 10000000000. 200. ("CFL number for the coupled flow equation system: ~a")) 
            (flow/scheme 21 integer #f 21 20 ("P-V coupling method:                             ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            )))
        ) 
        ("impl. Cou. num. IF (single-phase) DBNS incompressible" 180 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (not (cdr (assq 'rp-seg? (%rp-config #f)))) (not (is-compressible?)))) 
            (lambda () #t) 
            (courant-number/implicit 1000 real #f 1000 5. ("CFL value for the implicit dbns coupled solver:  ~a"))
        ) 
        ("impl. Cou. num. IF (single-phase) DBNS transient compressible" 200 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (not (cdr (assq 'rp-seg? (%rp-config #f)))) (cdr (assq 'rp-unsteady? (%rp-config #f))) (is-compressible?))) 
            (lambda () #t) 
            (courant-number/implicit 50 real #f 50 5. ("CFL value for the implicit dbns coupled solver:  ~a"))
        ) 
        ("PRESTO! IF (single-phase) PBNS steady buoyant OR swirl" 210 
            (lambda () (and (rpgetvar 'context/auto-detect?) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (not (cdr (assq 'rp-unsteady? (%rp-config #f)))) (or (and (cdr (assq 'rp-axi? (%rp-config #f))) (cdr (assq 'sg-swirl? (%rp-config #f)))) (have-boussinesq?)))) 
            (lambda () #t) 
            (pressure/scheme 14 integer #f 14 12 ("Spatial discretization for pressure:             ~a" (
                ("First Order Upwind" . 0) 
                ("Second Order Upwind" . 1) 
                ("Power Law" . 2) 
                ("Central Differencing" . 3) 
                ("QUICK" . 4) 
                ("Modified HRIC" . 5) 
                ("Third-Order MUSCL" . 6) 
                ("Bounded Central Differencing" . 7) 
                ("CICSAM" . 8) 
                ("Low Diffusion Second Order" . 9) 
                ("Standard" . 10) 
                ("Linear" . 11) 
                ("Second Order" . 12) 
                ("Body Force Weighted" . 13) 
                ("PRESTO!" . 14) 
                ("Continuity Based" . 15) 
                ("Geo-Reconstruct" . 16) 
                ("Donor-Acceptor" . 17) 
                ("Modified Body Force Weighted" . 18) 
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Coupled" . 24) 
                ("Fractional Step" . 25) 
                ("Compressive" . 28) 
                ("BGM" . 29) 
                ("Phase Coupled PISO" . 30) 
                ("Low Diffusion Central" . 31)
            )))
        ) 
        ("PRESTO! IF sing.-eq. multi-phase" 230 
            (lambda () (and (rpgetvar 'context/auto-detect?) (let ((sgm (cdr (assq 'sg-mphase? (%rp-config #f))))) (not (eq? sgm #f))))) 
            (lambda () #t) 
            (pressure/scheme 14 integer #f 14 12 ("Spatial discretization for pressure:             ~a" (
                ("First Order Upwind" . 0) 
                ("Second Order Upwind" . 1) 
                ("Power Law" . 2) 
                ("Central Differencing" . 3) 
                ("QUICK" . 4) 
                ("Modified HRIC" . 5) 
                ("Third-Order MUSCL" . 6) 
                ("Bounded Central Differencing" . 7) 
                ("CICSAM" . 8) 
                ("Low Diffusion Second Order" . 9) 
                ("Standard" . 10) 
                ("Linear" . 11) 
                ("Second Order" . 12) 
                ("Body Force Weighted" . 13) 
                ("PRESTO!" . 14) 
                ("Continuity Based" . 15) 
                ("Geo-Reconstruct" . 16) 
                ("Donor-Acceptor" . 17) 
                ("Modified Body Force Weighted" . 18) 
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Coupled" . 24) 
                ("Fractional Step" . 25) 
                ("Compressive" . 28) 
                ("BGM" . 29) 
                ("Phase Coupled PISO" . 30) 
                ("Low Diffusion Central" . 31)
            )))
        ) 
        ("Flow: transient; DPM: coupled" 10 
            (lambda () (and (cdr (assq 'rp-unsteady? (%rp-config #f))) (cdr (assq 'sg-dpm? (%rp-config #f))))) 
            (lambda () (or (cdr (assq 'sg-dpm? (%rp-config #f))) (dpm-bcs-available?))) 
            (dpm/sources-every-flow-iteration? #t boolean #f #t #f ("Update DPM source terms every flow iteration?:   ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("Flow: transient; DPM: unsteady, coupled" 12 
            (lambda () (and (cdr (assq 'sg-dpm? (%rp-config #f))) (and (cdr (assq 'rp-unsteady? (%rp-config #f))) (rpgetvar 'dpm/unsteady-tracking?)))) 
            (lambda () (or (cdr (assq 'sg-dpm? (%rp-config #f))) (dpm-bcs-available?))) 
            (dpm/relax 0.9 real #f 0.9 0.5 ("DPM source terms under-relaxation factor:        ~a"))
        ) 
        ("DPM: Unsteady" 14 
            (lambda () (rpgetvar 'dpm/unsteady-tracking?)) 
            (lambda () (or (cdr (assq 'sg-dpm? (%rp-config #f))) (dpm-bcs-available?))) 
            (dpm/max-steps 500 integer #f 500 50000 ("DPM maximum number of steps:                     ~a"))
        ) 
        ("DPM: barycentric interpolation of density and viscosity in multi-phase context" 100 
            (lambda () (cdr (assq 'sg-mphase? (%rp-config #f)))) 
            (lambda () (and (rpgetvar 'dpm/variable-interpolation/barycentric?) (or (cdr (assq 'sg-dpm? (%rp-config #f))) (dpm-bcs-available?)))) 
            (density/interpolate #t boolean #f #t #f ("Spatial interpolation for density:               ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (laminar-viscosity/interpolate #t boolean #f #t #f ("Spatial interpolation for laminar viscosity:     ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("VOF: Implicit and Steady State" 16 
            (lambda () (and (eq? (cdr (assq 'sg-mphase? (%rp-config #f))) 'vof) (not (cdr (assq 'rp-unsteady? (%rp-config #f)))) (eqv? (rpgetvar 'mp/scheme-type) 0))) 
            (lambda () #t) 
            (flow/scheme 24 integer #f 24 20 ("P-V coupling method:                             ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            ))) 
            (pseudo-transient-formulation? #t boolean #f #t #f ("Pseudo transient for steady state VOF:           ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("Wall Film: EWF with DPM collection" 18 
            (lambda () (if (and (rp-3d?) (cdr (assq 'rp-wallfilm? (%rp-config #f)))) (and (cdr (assq 'sg-wallfilm? (%rp-config #f))) (dpm-bcs-available?)) #f)) 
            (lambda () (if (and (rp-3d?) (cdr (assq 'rp-wallfilm? (%rp-config #f)))) (let* ((film-vars (rpgetvar 'wall-film/model-parameters)) (dpm-collection? (cdr (assq 'dpm-collection? film-vars))) (dpm-splashing? (cdr (assq 'dpm-splashing? film-vars))) (sg-wallfilm? (cdr (assq 'sg-wallfilm? (%rp-config #f))))) (or (not sg-wallfilm?) (and dpm-collection? dpm-splashing?))) #f)) 
            (dpm/orourke-splash-fraction? #f boolean #f #f #t ("O'Rourke splash fraction formulation:            ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (dpm/splash-pdf-tail-limiting? #f boolean #f #f #t ("Splash PDF distribution tail limiting:           ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("MP: NITA defaults" 20 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 23) (cdr (assq 'sg-noniterative? (%rp-config #f))))) 
            (lambda () #f) 
            (piso/neighbor-option 1 integer #f 1 0 ("Piso neighbor option:                            ~a")) 
            (piso/neighbor-add-option 1 integer #f 1 0 ("Piso neighbor add option:                        ~a")) 
            (piso/neighbor-iter 2 integer #f 2 1 ("Piso neighbor iterations:                        ~a")) 
            (mp/vof-piso-corrector? #t boolean #f #t #f ("Multiphase Piso vof corrector:                   ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("MP: NITA defaults r182a" 22 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 23) (cdr (assq 'sg-noniterative? (%rp-config #f))))) 
            (lambda () #f) 
            (pressure/max-iter 0 integer #f 0 10 ("Pressure skewness correction:                    ~a"))
        ) 
        ("MP: NITA defaults r190" 26 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 23) (cdr (assq 'sg-noniterative? (%rp-config #f))) (eqv? (rpgetvar 'mp/scheme-type) 0))) 
            (lambda () #f) 
            (mp/max-iter 1 integer #f 1 5 ("Max. no. of MP NITA sub iterations:              ~a"))
        ) 
        ("MP: NITA: override mp/max-iter from 'defaults r190' with higher number if mp/vof-piso-corrector is Off" 30 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 23) (cdr (assq 'sg-noniterative? (%rp-config #f))) (eqv? (rpgetvar 'mp/scheme-type) 0) (not (rpgetvar 'mp/vof-piso-corrector?)))) 
            (lambda () #f) 
            (mp/max-iter 5 integer #f 5 5 ("Max. no. of MP NITA sub iterations:              ~a"))
        ) 
        ("MP: NITA defaults r192" 27 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 23) (cdr (assq 'sg-noniterative? (%rp-config #f))))) 
            (lambda () #f) 
            (pressure/explicit-relax 0.5 real #f 0.5 1 ("Explicit Relaxation Factor for Pressure:         ~a")) 
            (mom/explicit-relax 0.7 real #f 0.7 1. ("Explicit Relaxation Factor for Momentum:         ~a"))
        ) 
        ("MP: NITA with POPULATION BALANCE" 34 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 23) (cdr (assq 'sg-noniterative? (%rp-config #f))) (cdr (assq 'sg-pb? (%rp-config #f))))) 
            (lambda () #f) 
            (pressure/explicit-relax 0.3 real #f 0.3 1 ("Explicit Relaxation Factor for Pressure:         ~a")) 
            (piso/number-of-correctors 2 integer #f 2 1 ("Number of PISO Correctors              :         ~a")) 
            (mp/nita/update-drag-coeff 1 integer #f 1 0 ("Update Drag Coeff                      :         ~a"))
        ) 
        ("DPM with NITA" 24 
            (lambda () (cdr (assq 'sg-noniterative? (%rp-config #f)))) 
            (lambda () (and (cdr (assq 'sg-dpm? (%rp-config #f))) (dpm-bcs-available?))) (dpm/relax 1. real #f 1. 0.5 ("DPM source term under-relaxation factor:         ~a"))
        ) 
        ("Aggressive NITA" 240 
            (lambda () (and (cdr (assq 'sg-noniterative? (%rp-config #f))) (rpgetvar 'nita/aggressive?) (not (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid)))) 
            (lambda () #f) 
            (pressure/max-iter 0 integer #f 0 10 ("Max. no. of Pressure NITA sub iterations:             ~a")) 
            (mom/max-iter 1 integer #f 1 5 ("Max. no. of Momentum NITA sub iterations:             ~a")) 
            (temperature/max-iter 1 integer #f 1 5 ("Max. no. of Temperature NITA sub iterations:          ~a")) 
            (enthalpy/max-iter 1 integer #f 1 5 ("Max. no. of Enthalpy sub iterations:                  ~a")) 
            (mp/max-iter 1 integer #f 1 5 ("Max. no. of Multiphase NITA sub iterations:           ~a")) 
            (potential/max-iter 1 integer #f 1 5 ("Max. no. of Potential NITA sub iterations:            ~a")) 
            (dqmom-iem/max-iter 1 integer #f 1 5 ("Max. no. of DQMOM NITA sub iterations:                ~a")) 
            (granular-temperature/max-iter 1 integer #f 1 5 ("Max. no. of Granular-Temperature NITA sub iterations: ~a")) 
            (w-swirl/max-iter 1 integer #f 1 5 ("Max. no. of Swirl NITA sub iterations:                ~a")) 
            (nut/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(NU) NITA sub iterations:       ~a")) 
            (k/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(K) NITA sub iterations:        ~a")) 
            (epsilon/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Epsilon) NITA sub iterations:  ~a")) 
            (v2/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(V2) NITA sub iterations:       ~a")) 
            (f/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(f) NITA sub iterations:        ~a")) 
            (kl/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(kl) NITA sub iterations:       ~a")) 
            (omega/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Omega) NITA sub iterations:    ~a")) 
            (intermit/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Intermit) NITA sub iterations: ~a")) 
            (retheta/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(retheta) NITA sub iterations:  ~a")) 
            (drsm/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(drsm) NITA sub iterations:     ~a")) 
            (fmean/max-iter 1 integer #f 1 5 ("Max. no. of fmean NITA sub iterations:                ~a")) 
            (fmean2/max-iter 1 integer #f 1 5 ("Max. no. of fmean2 NITA sub iterations:               ~a")) 
            (fvar/max-iter 1 integer #f 1 5 ("Max. no. of fvar NITA sub iterations:                 ~a")) 
            (fvar2/max-iter 1 integer #f 1 5 ("Max. no. of fvar2 NITA sub iterations:                ~a")) 
            (premixc/max-iter 1 integer #f 1 5 ("Max. no. of Premix NITA sub iterations:               ~a")) 
            (premix-g-eqn/max-iter 1 integer #f 1 5 ("Max. no. of Premix-G-Eq NITA sub iterations:          ~a")) 
            (premix-g-var/max-iter 1 integer #f 1 5 ("Max. no. of Premix-G-Var NITA sub iterations:         ~a")) 
            (pdftss/max-iter 1 integer #f 1 5 ("Max. no. of PDF-tss NITA sub iterations:              ~a")) 
            (pull/max-iter 1 integer #f 1 5 ("Max. no. of Pollutant NITA sub iterations:            ~a")) 
            (soot-mom/max-iter 1 integer #f 1 5 ("Max. no. of Soots NITA sub iterations:                ~a")) 
            (tvar/max-iter 1 integer #f 1 5 ("Max. no. of Tvar NITA sub iterations:                 ~a")) 
            (pressure/amg-alpha 0.01 real #f 0.01 0.1 ("Multigrid termination for the pressure:               ~a")) 
            (pressure/cycle-type 3 integer #f 3 1 ("Multigrid cycle type for the pressure:                ~a" (
                (0 . "Flexible") 
                (1 . "V-Cycle") 
                (2 . "W-Cycle") 
                (3 . "F-Cycle")
            ))) 
            (flow/scheme 25 integer #f 25 20 ("Flow Scheme is:                                       ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            ))) 
            (nita/flux/extrapolate? #t boolean #f #t #f ("Mass flux extrapolation:                              ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("constant density NITA" 241 
            (lambda () (and (cdr (assq 'sg-noniterative? (%rp-config #f))) (eqv? (rpgetvar 'nita/single-phase/hybrid/option) 1) (not (cdr (assq 'sg-mphase? (%rp-config #f)))))) 
            (lambda () #t) 
            (pressure/max-iter 0 integer #f 0 10 ("Max. no. of Pressure NITA sub iterations:             ~a")) 
            (mom/max-iter 1 integer #f 1 5 ("Max. no. of Momentum NITA sub iterations:             ~a")) 
            (temperature/max-iter 1 integer #f 1 5 ("Max. no. of Temperature NITA sub iterations:          ~a")) 
            (enthalpy/max-iter 1 integer #f 1 5 ("Max. no. of Enthalpy sub iterations:                  ~a")) 
            (w-swirl/max-iter 1 integer #f 1 5 ("Max. no. of Swirl NITA sub iterations:                ~a")) 
            (nut/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(NU) NITA sub iterations:       ~a")) 
            (k/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(K) NITA sub iterations:        ~a")) 
            (epsilon/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Epsilon) NITA sub iterations:  ~a")) 
            (v2/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(V2) NITA sub iterations:       ~a")) 
            (f/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(f) NITA sub iterations:        ~a")) 
            (kl/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(kl) NITA sub iterations:       ~a")) 
            (omega/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Omega) NITA sub iterations:    ~a")) 
            (intermit/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Intermit) NITA sub iterations: ~a")) 
            (retheta/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(retheta) NITA sub iterations:  ~a")) 
            (drsm/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(drsm) NITA sub iterations:     ~a")) 
            (fmean/max-iter 1 integer #f 1 5 ("Max. no. of fmean NITA sub iterations:                ~a")) 
            (fmean2/max-iter 1 integer #f 1 5 ("Max. no. of fmean2 NITA sub iterations:               ~a")) 
            (fvar/max-iter 1 integer #f 1 5 ("Max. no. of fvar NITA sub iterations:                 ~a")) 
            (fvar2/max-iter 1 integer #f 1 5 ("Max. no. of fvar2 NITA sub iterations:                ~a")) 
            (premixc/max-iter 1 integer #f 1 5 ("Max. no. of Premix NITA sub iterations:               ~a")) 
            (premix-g-eqn/max-iter 1 integer #f 1 5 ("Max. no. of Premix-G-Eq NITA sub iterations:          ~a")) 
            (premix-g-var/max-iter 1 integer #f 1 5 ("Max. no. of Premix-G-Var NITA sub iterations:         ~a")) 
            (pdftss/max-iter 1 integer #f 1 5 ("Max. no. of PDF-tss NITA sub iterations:              ~a")) 
            (pull/max-iter 1 integer #f 1 5 ("Max. no. of Pollutant NITA sub iterations:            ~a")) 
            (soot-mom/max-iter 1 integer #f 1 5 ("Max. no. of Soots NITA sub iterations:                ~a")) 
            (tvar/max-iter 1 integer #f 1 5 ("Max. no. of Tvar NITA sub iterations:                 ~a")) 
            (pressure/cycle-type 3 integer #f 3 1 ("Multigrid cycle type for the pressure:                ~a" (
                (0 . "Flexible") 
                (1 . "V-Cycle") 
                (2 . "W-Cycle") 
                (3 . "F-Cycle")
            ))) 
            (pressure/amg-alpha 0.01 real #f 0.01 0.1 ("Multigrid termination for the pressure:               ~a")) 
            (mom/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for momentum:                 ~a")) 
            (pressure/residual-tolerance 0.01 real #f 0.01 0.0001 ("Residual-tolerance for pressure:                 ~a")) 
            (temperature/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for temperature:              ~a")) 
            (enthalpy/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for enthalpy:                 ~a")) 
            (w-swirl/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for w-swirl:                  ~a")) 
            (nut/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (nu):          ~a")) 
            (k/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (k):           ~a")) 
            (epsilon/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (epsilon):     ~a")) 
            (v2/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (V2):          ~a")) 
            (f/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (f):           ~a")) 
            (kl/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (kl):          ~a")) 
            (omega/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (Omega):       ~a")) 
            (intermit/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (Intermit):    ~a")) 
            (retheta/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (retheta):     ~a")) 
            (drsm/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (drsm):       ~a")) 
            (flow/scheme 25 integer #f 25 20 ("Flow Scheme is:                                       ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            ))) 
            (nita/flux/extrapolate? #t boolean #f #t #f ("Mass flux extrapolation:                              ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (nita/residual-tolerance/iter 2 integer #f 2 1 ("Number of iterations with residual-tolerance:         ~a")) 
            (nita/outer-iter 2 integer #f 2 1 ("Max. no. of outer iterations:                         ~a")) 
            (mom/relax 1 real #f 1 0.7 ("Under-relaxation for momentum             ~a")) 
            (pressure/relax 1 real #f 1 0.3 ("Under-relaxation for pressure             ~a")) 
            (w-swirl/relax 1 real #f 1 0.9 ("Under-relaxation for swirl                ~a")) 
            (nut/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(nut)      ~a")) 
            (k/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(k)        ~a")) 
            (epsilon/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(epsilon)  ~a")) 
            (v2/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(v2)       ~a")) 
            (f/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(f)        ~a")) 
            (kl/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(kl)       ~a")) 
            (omega/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(omega)    ~a")) 
            (intermit/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(intermit) ~a")) 
            (retheta/relax 1 real #f 1 0.8 ("Under-relaxation for turbulence(retheta)  ~a")) 
            (drsm/relax 1 real #f 1 0.5 ("Under-relaxation for turbulence(dtrsm)    ~a"))
        ) 
        ("variable density NITA" 242 
            (lambda () (and (cdr (assq 'sg-noniterative? (%rp-config #f))) (eqv? (rpgetvar 'nita/single-phase/hybrid/option) 2) (not (cdr (assq 'sg-mphase? (%rp-config #f)))))) 
            (lambda () #t) 
            (pressure/max-iter 0 integer #f 0 10 ("Max. no. of Pressure NITA sub iterations:             ~a")) 
            (mom/max-iter 1 integer #f 1 5 ("Max. no. of Momentum NITA sub iterations:             ~a")) 
            (temperature/max-iter 1 integer #f 1 5 ("Max. no. of Temperature NITA sub iterations:          ~a")) 
            (enthalpy/max-iter 1 integer #f 1 5 ("Max. no. of Enthalpy sub iterations:                  ~a")) 
            (species/max-iter (1) integer-list #f (1) (5) ("Max. no. of Species  sub iterations:                  ~a")) 
            (w-swirl/max-iter 1 integer #f 1 5 ("Max. no. of Swirl NITA sub iterations:                ~a")) 
            (nut/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(NU) NITA sub iterations:       ~a")) 
            (k/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(K) NITA sub iterations:        ~a")) 
            (epsilon/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Epsilon) NITA sub iterations:  ~a")) 
            (v2/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(V2) NITA sub iterations:       ~a")) 
            (f/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(f) NITA sub iterations:        ~a")) 
            (kl/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(kl) NITA sub iterations:       ~a")) 
            (omega/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Omega) NITA sub iterations:    ~a")) 
            (intermit/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(Intermit) NITA sub iterations: ~a")) 
            (retheta/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(retheta) NITA sub iterations:  ~a")) 
            (drsm/max-iter 1 integer #f 1 5 ("Max. no. of Turbulence(drsm) NITA sub iterations:     ~a")) 
            (fmean/max-iter 1 integer #f 1 5 ("Max. no. of fmean NITA sub iterations:                ~a")) 
            (fmean2/max-iter 1 integer #f 1 5 ("Max. no. of fmean2 NITA sub iterations:               ~a")) 
            (fvar/max-iter 1 integer #f 1 5 ("Max. no. of fvar NITA sub iterations:                 ~a")) 
            (fvar2/max-iter 1 integer #f 1 5 ("Max. no. of fvar2 NITA sub iterations:                ~a")) 
            (premixc/max-iter 1 integer #f 1 5 ("Max. no. of Premix NITA sub iterations:               ~a")) 
            (premix-g-eqn/max-iter 1 integer #f 1 5 ("Max. no. of Premix-G-Eq NITA sub iterations:          ~a")) 
            (premix-g-var/max-iter 1 integer #f 1 5 ("Max. no. of Premix-G-Var NITA sub iterations:         ~a")) 
            (pdftss/max-iter 1 integer #f 1 5 ("Max. no. of PDF-tss NITA sub iterations:              ~a")) 
            (pull/max-iter 1 integer #f 1 5 ("Max. no. of Pollutant NITA sub iterations:            ~a")) 
            (soot-mom/max-iter 1 integer #f 1 5 ("Max. no. of Soots NITA sub iterations:                ~a")) 
            (tvar/max-iter 1 integer #f 1 5 ("Max. no. of Tvar NITA sub iterations:                 ~a")) 
            (pressure/cycle-type 3 integer #f 3 1 ("Multigrid cycle type for the pressure:                ~a" (
                (0 . "Flexible") 
                (1 . "V-Cycle") 
                (2 . "W-Cycle") 
                (3 . "F-Cycle")
            ))) 
            (pressure/amg-alpha 0.01 real #f 0.01 0.1 ("Multigrid termination for the pressure       :        ~a")) 
            (mom/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for momentum:                 ~a")) 
            (pressure/residual-tolerance 0.01 real #f 0.01 0.0001 ("Residual-tolerance for pressure:                 ~a")) 
            (temperature/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for temperature:              ~a")) 
            (enthalpy/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for enthalpy:                 ~a")) 
            (w-swirl/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for w-swirl:                  ~a")) 
            (nut/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (nu):          ~a")) 
            (k/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (k):           ~a")) 
            (epsilon/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (epsilon):     ~a")) 
            (v2/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (V2):          ~a")) 
            (f/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (f):           ~a")) 
            (kl/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (kl):          ~a")) 
            (omega/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (Omega):       ~a")) 
            (intermit/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (Intermit):    ~a")) 
            (retheta/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (retheta):     ~a")) 
            (drsm/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for turbulence (drsm):        ~a")) 
            (species/residual-tolerance (0.001) real-list #f (0.001) (0.0001) ("Residual-tolerance for species:                  ~a")) 
            (potential/residual-tolerance 0.001 real #f 0.001 1e-06 ("Residual-tolerance for potential:                ~a")) 
            (dqmom-iem/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for DQMOM:                    ~a")) 
            (fmean/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for fmean:                    ~a")) 
            (fmean2/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for fmean2:                   ~a")) 
            (fvar/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for fvar:                     ~a")) 
            (fvar2/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for fvar2:                    ~a")) 
            (premixc/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for premixc:                  ~a")) 
            (pdftss/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for pdftss:                   ~a")) 
            (pull/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for pull:                     ~a")) 
            (soot-mom/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for soot-mom:                 ~a")) 
            (tvar/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for tvar:                     ~a")) 
            (premix-g-eqn/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for premix-g-eqn:            ~a")) 
            (premix-g-var/residual-tolerance 0.001 real #f 0.001 0.0001 ("Residual-tolerance for premix-g-var:            ~a")) 
            (flow/scheme 25 integer #f 25 20 ("Flow Scheme is:                                       ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            ))) 
            (nita/flux/extrapolate? #f boolean #f #f #f ("Mass flux extrapolation:                              ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (nita/outer-iter 10 integer #f 10 1 ("Max. no. of outer iterations:                         ~a")) 
            (models/equation-order 1 integer #f 1 0 ("Changing equation order                               ~a" (
                ("Standard" . 0) 
                ("Optimized-for-volumetric-expansion" . 1)
            ))) 
            (density/relax 0.75 real #f 0.75 1 ("Under-Relaxation Factor for density                   ~a")) 
            (dpm/relax 0.75 real #f 0.75 0.5 ("DPM source terms under-relaxation factor:             ~a")) 
            (fvar/relax 0.9 real #f 0.9 0.9 ("Under-relaxation factor for mean-fraction             ~a")) 
            (mom/relax 0.75 real #f 0.75 0.7 ("Under-Relaxation Factor for momentum                 ~a")) 
            (premixc/relax 0.9 real #f 0.9 0.9 ("Under-relaxation factor for premix-c                  ~a")) 
            (pressure/relax 0.75 real #f 0.75 0.3 ("Under-Relaxation Factor for pressure  ~a"))
        ) 
        ("Multi Phase PISO" 32 
            (lambda () (and (equal? (cdr (assq 'sg-mphase? (%rp-config #f))) 'multi-fluid) (eqv? (rpgetvar 'flow/scheme) 30))) 
            (lambda () #f) 
            (pressure/max-iter 0 integer #f 0 10 ("Pressure skewness correction:         ~a")) 
            (piso/coupling? #f boolean #f #f #t ("Skewness neighbor coupling:           ~a"))
        ) 
        ("Fast Transient SIMPLEC" 243 
            (lambda () (and (or (cdr (assq 'sg-pdf? (%rp-config #f))) (cdr (assq 'sg-par-premix? (%rp-config #f)))) (cdr (assq 'rp-unsteady? (%rp-config #f))) (not (cdr (assq 'sg-noniterative? (%rp-config #f)))) (rpgetvar 'pdf/activate-ft-simplec?))) 
            (lambda () #f) 
            (models/equation-order 1 integer #f 1 0 ("Equation order:                              ~a" (
                ("Standard" . 0) 
                ("Optimized-for-volumetric-expansion" . 1)
            ))) 
            (flow/scheme 21 integer #f 21 20 ("P-V coupling method is:                      ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            ))) 
            (pressure/cycle-type 3 integer #f 3 1 ("AMG cycle type for pressure equation:          ~a" (
                (0 . "Flexible") 
                (1 . "V-Cycle") 
                (2 . "W-Cycle") 
                (3 . "F-Cycle")
            ))) 
            (pressure/scheme 12 integer #f 12 12 ("Pressure discretization scheme:                ~a" (
                ("First Order Upwind" . 0) 
                ("Second Order Upwind" . 1) 
                ("Power Law" . 2) 
                ("Central Differencing" . 3) 
                ("QUICK" . 4) 
                ("Modified HRIC" . 5) 
                ("Third-Order MUSCL" . 6) 
                ("Bounded Central Differencing" . 7) 
                ("CICSAM" . 8) 
                ("Low Diffusion Second Order" . 9) 
                ("Standard" . 10) 
                ("Linear" . 11) 
                ("Second Order" . 12) 
                ("Body Force Weighted" . 13) 
                ("PRESTO!" . 14) 
                ("Continuity Based" . 15) 
                ("Geo-Reconstruct" . 16) 
                ("Donor-Acceptor" . 17) 
                ("Modified Body Force Weighted" . 18) 
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Coupled" . 24) 
                ("Fractional Step" . 25) 
                ("Compressive" . 28) 
                ("BGM" . 29) 
                ("Phase Coupled PISO" . 30) 
                ("Low Diffusion Central" . 31)
            ))) 
            (pressure/amg-alpha 0.01 real #f 0.01 0.1 ("Multigrid termination for the pressure:          ~a")) 
            (pressure/relax 0.75 real #f 0.75 0.3 ("Under-Relaxation Factor for pressure:            ~a")) 
            (mom/relax 0.75 real #f 0.75 0.7 ("Under-Relaxation Factor for momentum:            ~a")) 
            (dpm/relax 0.75 real #f 0.75 0.5 ("Under-Relaxation Factor for dpm:                 ~a")) 
            (density/relax 0.75 real #f 0.75 1 ("Under-Relaxation Factor for density:             ~a")) 
            (max-iterations-per-step 10 integer #f 10 20 ("Max. no. of iterations per time step:            ~a"))
        ) 
        ("FGM Robustness Improvements" 244 
            (lambda () (and (cdr (assq 'sg-par-premix? (%rp-config #f))) (cdr (assq 'rp-unsteady? (%rp-config #f))) (rpgetvar 'prepdf/prmx-flamelet?) (eqv? (rpgetvar 'pdf/prmx-fla-turb-chem-model) 0) (cdr (assq 'sg-dpm? (%rp-config #f))))) 
            (lambda () #f) 
            (premixc/fgm-src-method-1? #t boolean #f #t #f ("Enable convergence method 1:                     ~a"))
        ) 
        ("DBNS Poor Mesh Numerics" 245 
            (lambda () (and (not (rp-seg?)) (rpgetvar 'mesh/bad/tmp-enhanced-pmn?))) 
            (lambda () #f) 
            (mesh/bad/enable-quality-based-treatment? #t boolean #f #t #f ("Quality Based Treatment?: ~a")) 
            (mesh/bad/min-orthogonal-quality 0.2 real #f 0.2 0.05 ("Min Orthogonal Quality:   ~a")) 
            (mesh/bad/tmp-limit-cfl? #t boolean #f #t #f ("Limit CFL?:               ~a")) 
            (mesh/bad/tmp-cfl-limit 1. real #f 1. 1. ("CFL Limit:                ~a")) 
            (mesh/bad/repair-sltn-mode 0 integer #f 0 0 ("Solution repair mode:     ~a")) 
            (mesh/bad/repair-grad-mode 2 integer #f 2 2 ("Gradient repair mode:     ~a"))
        ) 
        ("Pseudo Time Method" 2000 
            (lambda () (and (cdr (assq 'rp-seg? (%rp-config #f))) (not (eqv? (rpgetvar 'flow/scheme) 24)))) 
            (lambda () #f) 
            (pseudo-transient-formulation? #f boolean #f #f #t ("Pseudo transient: ~a"))
        ) 
        ("Pseudo Time Method Transient" 2001 
            (lambda () (and (cdr (assq 'rp-unsteady? (%rp-config #f))) (rpgetvar 'show-beta-features?))) 
            (lambda () #f) 
            (pseudo-transient-formulation? #f boolean #f #f #f ("Pseudo time method is disabled: ~a"))
        ) 
        ("Pseudo Time Method Mode" 2002 
            (lambda () (or (and (cdr (assq 'rp-seg? (%rp-config #f))) (eqv? (rpgetvar 'flow/scheme) 24)) (cdr (assq 'rp-amg? (%rp-config #f))))) 
            (lambda () #f) 
            (pseudo-transient-mode 0 integer #f 0 0 ("Pseudo transient Time Step Mode: ~a"))
        ) 
        ("Default Local Pseudo Time AMG Controls" 246 
            (lambda () (or (eqv? (rpgetvar 'pseudo-time-method/segregated-pbns/dt-method) 2) (eqv? (rpgetvar 'pseudo-time-method/coupled-pbns/dt-method) 2) (eqv? (rpgetvar 'pseudo-time-method/implicit-dbns/dt-method) 2))) 
            (lambda () #f) 
            (pressure/dual-ts-cycle-type 1 integer #f 1 1 ("AMG cycle type for Pressure equation:       ~a" ,cycle-map)) 
            (x-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for X-Momentum equation:     ~a" ,cycle-map)) 
            (y-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Y-Momentum equation:     ~a" ,cycle-map)) 
            (z-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Z-Momentum equation:     ~a" ,cycle-map)) 
            (w-swirl/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Swirl equation:          ~a" ,cycle-map)) 
            (temperature/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Temperature equation:    ~a" ,cycle-map)) 
            (enthalpy/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Enthalpy equation:       ~a" ,cycle-map)) 
            (tvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Tvar equation:           ~a" ,cycle-map)) 
            (k/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for K equation:              ~a" ,cycle-map)) 
            (epsilon/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Epsilon equation:        ~a" ,cycle-map)) 
            (omega/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Omega equation:          ~a" ,cycle-map)) 
            (kl/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for KL equation:             ~a" ,cycle-map)) 
            (nut/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Nut equation:            ~a" ,cycle-map)) 
            (drsm/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for DRSM equation:           ~a" ,cycle-map)) 
            (retheta/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Retheta equation:        ~a" ,cycle-map)) 
            (intermit/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Intermit equation:       ~a" ,cycle-map)) 
            (v2/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for V2 equation:             ~a" ,cycle-map)) 
            (f/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for F equation:              ~a" ,cycle-map)) 
            (fmean/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fmean equation:          ~a" ,cycle-map)) 
            (fmean2/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fmean2 equation:         ~a" ,cycle-map)) 
            (fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fvar equation:           ~a" ,cycle-map)) 
            (fvar2/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fvar2 equation:          ~a" ,cycle-map)) 
            (premixc/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Premixc equation:        ~a" ,cycle-map)) 
            (premix-g-var/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Premix-G-var equation:   ~a" ,cycle-map)) 
            (pdftss/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for PDF-tss equation:        ~a" ,cycle-map)) 
            (sootspecies/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Soot-Species equation:   ~a" ,cycle-map)) 
            (soot-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Soot-Mom equation:       ~a" ,cycle-map)) 
            (inert/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Inert equation:          ~a" ,cycle-map)) 
            (ic-fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for IC-Fvar equation:        ~a" ,cycle-map)) 
            (vc-fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for VC-Fvar equation:        ~a" ,cycle-map)) 
            (vd-fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for VD-Fvar equation:        ~a" ,cycle-map)) 
            (potential/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Potential equation:      ~a" ,cycle-map)) 
            (potential-2/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Electrolyte Potential equation:      ~a" ,cycle-map)) 
            (watercontent/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Water Content equation:      ~a" ,cycle-map)) 
            (lithium/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Lithium equation:        ~a" ,cycle-map)) 
            (ecfm-sigma/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for ECFM-Sigma equation:     ~a" ,cycle-map)) 
            (pollutant/dual-ts-cycle-type (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) integer-list #f (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) ("AMG cycle type for Pollutant equation:      ~a"))
        ) 
        ("Coupled Local Pseudo Time AMG Controls" 247 
            (lambda () (and (eqv? (rpgetvar 'flow/scheme) 24) (cdr (assq 'rp-seg? (%rp-config #f))) (eqv? (rpgetvar 'pseudo-time-method/coupled-pbns/dt-method) 2) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (not (cdr (assq 'rp-react? (%rp-config #f)))) (not (cdr (assq 'rp-structure? (%rp-config #f)))) (not (cdr (assq 'sg-wetsteam? (%rp-config #f)))) (not (cdr (assq 'sg-crev? (%rp-config #f)))) (not (cdr (assq 'sg-geqn? (%rp-config #f)))) (not (cdr (assq 'sg-dqmom-iem? (%rp-config #f)))) (not (cdr (assq 'sg-noniterative? (%rp-config #f)))))) 
            (lambda () #f) 
            (w-swirl/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Swirl equation:          ~a" ,cycle-map)) 
            (temperature/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Temperature equation:    ~a" ,cycle-map)) 
            (enthalpy/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Enthalpy equation:       ~a" ,cycle-map)) 
            (tvar/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Tvar equation:           ~a" ,cycle-map)) 
            (k/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for K equation:              ~a" ,cycle-map)) 
            (epsilon/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Epsilon equation:        ~a" ,cycle-map)) 
            (omega/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Omega equation:          ~a" ,cycle-map)) 
            (kl/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for KL equation:             ~a" ,cycle-map)) 
            (nut/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Nut equation:            ~a" ,cycle-map)) 
            (drsm/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for DRSM equation:           ~a" ,cycle-map)) 
            (retheta/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Retheta equation:        ~a" ,cycle-map)) 
            (intermit/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Intermit equation:       ~a" ,cycle-map)) 
            (v2/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for V2 equation:             ~a" ,cycle-map)) 
            (f/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for F equation:              ~a" ,cycle-map)) 
            (fmean/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Fmean equation:          ~a" ,cycle-map)) 
            (fmean2/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Fmean2 equation:         ~a" ,cycle-map)) 
            (fvar/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Fvar equation:           ~a" ,cycle-map)) 
            (fvar2/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Fvar2 equation:          ~a" ,cycle-map)) 
            (premixc/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Premixc equation:        ~a" ,cycle-map)) 
            (premix-g-var/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Premix-G-var equation:   ~a" ,cycle-map)) 
            (pdftss/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for PDF-tss equation:        ~a" ,cycle-map)) 
            (sootspecies/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Soot-Species equation:   ~a" ,cycle-map)) 
            (soot-mom/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Soot-Mom equation:       ~a" ,cycle-map)) 
            (inert/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for Inert equation:          ~a" ,cycle-map)) 
            (ic-fvar/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for IC-Fvar equation:        ~a" ,cycle-map)) 
            (vc-fvar/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for VC-Fvar equation:        ~a" ,cycle-map)) 
            (vd-fvar/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for VD-Fvar equation:        ~a" ,cycle-map)) 
            (potential/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Potential equation:      ~a" ,cycle-map)) 
            (potential-2/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Electrolyte Potential equation:      ~a" ,cycle-map)) 
            (watercontent/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Water Content equation:      ~a" ,cycle-map)) 
            (lithium/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Lithium equation:        ~a" ,cycle-map)) 
            (ecfm-sigma/dual-ts-cycle-type 3 integer #f 3 0 ("AMG cycle type for ECFM-Sigma equation:     ~a" ,cycle-map)) 
            (pollutant/dual-ts-cycle-type (3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3) integer-list #f (3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3) (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) ("AMG cycle type for Pollutant equation:      ~a"))
        ) 
        ("Segregated Local Pseudo Time AMG Controls" 248 
            (lambda () (and (not (eqv? (rpgetvar 'flow/scheme) 24)) (cdr (assq 'rp-seg? (%rp-config #f))) (eqv? (rpgetvar 'pseudo-time-method/segregated-pbns/dt-method) 2) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (not (cdr (assq 'rp-react? (%rp-config #f)))) (not (cdr (assq 'rp-structure? (%rp-config #f)))) (not (cdr (assq 'sg-wetsteam? (%rp-config #f)))) (not (cdr (assq 'sg-crev? (%rp-config #f)))) (not (cdr (assq 'sg-geqn? (%rp-config #f)))) (not (cdr (assq 'sg-dqmom-iem? (%rp-config #f)))) (not (cdr (assq 'sg-noniterative? (%rp-config #f)))))) 
            (lambda () #f) 
            (pressure/dual-ts-cycle-type 1 integer #f 1 1 ("AMG cycle type for Pressure equation:       ~a" ,cycle-map)) 
            (x-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for X-Momentum equation:     ~a" ,cycle-map)) 
            (y-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Y-Momentum equation:     ~a" ,cycle-map)) 
            (z-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Z-Momentum equation:     ~a" ,cycle-map)) 
            (w-swirl/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Swirl equation:          ~a" ,cycle-map)) 
            (temperature/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Temperature equation:    ~a" ,cycle-map)) 
            (enthalpy/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Enthalpy equation:       ~a" ,cycle-map)) 
            (tvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Tvar equation:           ~a" ,cycle-map)) 
            (k/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for K equation:              ~a" ,cycle-map)) 
            (epsilon/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Epsilon equation:        ~a" ,cycle-map)) 
            (omega/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Omega equation:          ~a" ,cycle-map)) 
            (kl/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for KL equation:             ~a" ,cycle-map)) 
            (nut/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Nut equation:            ~a" ,cycle-map)) 
            (drsm/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for DRSM equation:           ~a" ,cycle-map)) 
            (retheta/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Retheta equation:        ~a" ,cycle-map)) 
            (intermit/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Intermit equation:       ~a" ,cycle-map)) 
            (v2/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for V2 equation:             ~a" ,cycle-map)) 
            (f/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for F equation:              ~a" ,cycle-map)) 
            (fmean/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fmean equation:          ~a" ,cycle-map)) 
            (fmean2/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fmean2 equation:         ~a" ,cycle-map)) 
            (fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fvar equation:           ~a" ,cycle-map)) 
            (fvar2/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Fvar2 equation:          ~a" ,cycle-map)) 
            (premixc/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Premixc equation:        ~a" ,cycle-map)) 
            (premix-g-var/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Premix-G-var equation:   ~a" ,cycle-map)) 
            (pdftss/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for PDF-tss equation:        ~a" ,cycle-map)) 
            (sootspecies/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Soot-Species equation:   ~a" ,cycle-map)) 
            (soot-mom/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Soot-Mom equation:       ~a" ,cycle-map)) 
            (inert/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for Inert equation:          ~a" ,cycle-map)) 
            (ic-fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for IC-Fvar equation:        ~a" ,cycle-map)) 
            (vc-fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for VC-Fvar equation:        ~a" ,cycle-map)) 
            (vd-fvar/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for VD-Fvar equation:        ~a" ,cycle-map)) 
            (potential/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Potential equation:      ~a" ,cycle-map)) 
            (potential-2/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Electrolyte Potential equation:      ~a" ,cycle-map)) 
            (watercontent/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Water Content equation:      ~a" ,cycle-map)) 
            (lithium/dual-ts-cycle-type 3 integer #f 3 3 ("AMG cycle type for Lithium equation:        ~a" ,cycle-map)) 
            (ecfm-sigma/dual-ts-cycle-type 0 integer #f 0 0 ("AMG cycle type for ECFM-Sigma equation:     ~a" ,cycle-map)) 
            (pollutant/dual-ts-cycle-type (3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3) integer-list #f (3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3) (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) ("AMG cycle type for Pollutant equation:      ~a"))
        ) 
        ("preview-defaults" 1000 
            (lambda () (rpgetvar 'solver/mode/preview-defaults)) 
            (lambda () #f)
        ) 
        ("fast" 1000 
            (lambda () (rpgetvar 'solver/mode/fast)) 
            (lambda () #f)
        ) 
        ("robust" 1000 
            (lambda () (rpgetvar 'solver/mode/robust)) 
            (lambda () #f)
        ) 
        ("preview-defaults-base" 1003 
            (lambda () (rpgetvar 'solver/mode/preview-defaults)) 
            (lambda () #t) 
            (amg-coupled/greedy-coarsening? #t boolean #f #t #f ("Aggressive AMG coarsening for coupled equations: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (amg/greedy-coarsening? #t boolean #f #t #f ("Aggressive AMG coarsening for scalar equations: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (amg-coupled/group-method-fallback 2 integer #f 2 0) 
            (amg/group-method-fallback 2 integer #f 2 0) 
            (amg-coupled/group-size-3d 6 integer #f 6 8 ("AMG Group size for coupled equations: ~a")) 
            (amg-scalar/group-size-3d 6 integer #f 6 8 ("AMG Group size for scalar equations: ~a")) 
            (partition/auto/laplace/check-aspect-ratio 100. real #f 100. 100 ("Laplace partitioning's checker cutoff aspect ratio: ~a")) 
            (partition/auto/laplace/aspect-ratio 10. real #f 10. 10 ("Laplace partitioning cutoff aspect ratio: ~a"))
        ) 
        ("preview-defaults-transient-pbns-base" 1003 
            (lambda () (and (cdr (assq 'rp-unsteady? (%rp-config #f))) (cdr (assq 'rp-seg? (%rp-config #f))) (rpgetvar 'solver/mode/preview-defaults))) 
            (lambda () #t) 
            (pressure/relax 0.8 real #f 0.8 0.3 ("Under-Relaxation Factor for pressure: ~a")) 
            (mom/relax 0.7 real #f 0.7 0.7 ("Under-Relaxation Factor for momentum: ~a")) 
            (simplec/skew-iter 1 integer #f 1 0 ("Skewness Correction for SIMPLEC: ~a")) 
            (density/relax 1 real #f 1 1 ("Under-Relaxation Factor for density: ~a")) 
            (density/pseudo-relax 1 real #f 1 1.) 
            (pressure-coupled/courant-number 10000000000. real #f 10000000000. 200. ("CFL number for the coupled flow equation system: ~a")) 
            (flow/scheme 21 integer #f 21 20 ("Pressure-velocity coupling: ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            )))
        ) 
        ("robust-base" 1000 
            (lambda () (rpgetvar 'solver/mode/robust)) 
            (lambda () #t) 
            (pressure/presto/limit-pgrad? #t boolean #f #t #f ("Limit high order terms in PRESTO!: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (mesh/bad/enable-quality-based-treatment? #t boolean #f #t #f ("Enable poor mesh numerics based on cell quality: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (amg/divergence-epsilon 1000000. real #f 1000000. 1000. ("AMG divergence epsilon: ~a")) 
            (partition/laplace/use? #t boolean #f #t #f ("Use Laplace partitioning: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            )))
        ) 
        ("fast-base" 1000 
            (lambda () (rpgetvar 'solver/mode/fast)) 
            (lambda () #t)
        ) 
        ("coupled-pseudo-transient" 1001 
            (lambda () (and (rpgetvar 'solver/mode/coupled-pseudo-transient) (and (not (cdr (assq 'rp-unsteady? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (not (gpuapp-enabled?)) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (not (cdr (assq 'sg-melt? (%rp-config #f)))) (not (or (rpgetvar 'battery/model0-loaded?) (rpgetvar 'battery/model-loaded?) (rpgetvar 'resolved-fc-model-loaded?) (rpgetvar 'sofc_01/sofc-loaded?) (rpgetvar 'pemfc-model-loaded?)))))) 
            (lambda () #f) 
            (flow/scheme 24 integer #f 24 20 ("Pressure-velocity coupling: ~a" (
                ("SIMPLE" . 20) 
                ("SIMPLEC" . 21) 
                ("PISO" . 22) 
                ("Fractional Step" . 25) 
                ("Coupled" . 24) 
                ("Phase Coupled SIMPLE" . 23) 
                ("Phase Coupled PISO" . 30)
            ))) 
            (pseudo-transient-formulation? #t boolean #f #t #f ("Pseudo-transient: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (amg-coupled/greedy-coarsening? #t boolean #f #t #f ("Aggressive AMG coarsening for coupled equations: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (amg/greedy-coarsening? #t boolean #f #t #f ("Aggressive AMG coarsening for segregated equations: ~a" (
                ("enabled" . #t) 
                ("disabled" . #f)
            ))) 
            (amg-coupled/group-size-3d 6 integer #f 6 8 ("AMG group size for coupled equations: ~a")) 
            (amg-scalar/group-size-3d 6 integer #f 6 8 ("AMG group size for segregated equations: ~a"))
        ) 
        ("reacting-flow-numerics" 1003 
            (lambda () (and (rpgetvar 'solver/mode/coupled-pseudo-transient) (not (cdr (assq 'rp-unsteady? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (= (rpgetvar 'flow/scheme) 24) (eqv? (rpgetvar 'pseudo-time-method/coupled-pbns/dt-method) 1) (or (cdr (assq 'rp-react? (%rp-config #f))) (cdr (assq 'sg-pdf? (%rp-config #f))) (cdr (assq 'sg-pdf-transport? (%rp-config #f))) (cdr (assq 'sg-premixed? (%rp-config #f))) (cdr (assq 'sg-par-premix? (%rp-config #f)))))) 
            (lambda () #t) 
            (density/pseudo-relax 0.25 real #f 0.25 1. ("Density explicit underrelaxation factor: ~a")) 
            (temperature/pseudo-specific? #t boolean #f #t #t) 
            (tvar/pseudo-specific? #t boolean #f #t #f) 
            (enthalpy/pseudo-specific? #t boolean #f #t #f) 
            (species/pseudo-specific? (#t) boolean-list #f (#t) (#f)) 
            (pollutant/pseudo-specific? (#t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t) boolean-list #f (#t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t) (#f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f)) 
            (temperature/pseudo-time-scale-factor 1e+20 real #f 1e+20 1.) 
            (tvar/pseudo-time-scale-factor 1e+20 real #f 1e+20 1.) 
            (enthalpy/pseudo-time-scale-factor 1e+20 real #f 1e+20 1.) 
            (species/pseudo-time-scale-factor (1e+20) real-list #f (1e+20) (1.)) 
            (pollutant/pseudo-time-scale-factor (1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20) real-list #f (1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20 1e+20) (1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.))
        ) 
        ("species-numerics" 1002 
            (lambda () (and (rpgetvar 'solver/mode/coupled-pseudo-transient) (not (cdr (assq 'rp-unsteady? (%rp-config #f)))) (cdr (assq 'rp-seg? (%rp-config #f))) (not (cdr (assq 'sg-mphase? (%rp-config #f)))) (= (rpgetvar 'flow/scheme) 24) (eqv? (rpgetvar 'pseudo-time-method/coupled-pbns/dt-method) 1) (cdr (assq 'rp-spe? (%rp-config #f))) (cdr (assq 'rp-seg? (%rp-config #f))))) 
            (lambda () #t) 
            (density/pseudo-relax 0.25 real #f 0.25 1. ("Density explicit underrelaxation factor: ~a"))
        ) 
        ("tight-amg" 1000 
            (lambda () (rpgetvar 'solver/mode/tight-amg)) 
            (lambda () #t) 
            (amg-coupled/max-cycles 100 integer #f 100 10 ("Max cycles for coupled systems: ~a")) 
            (amg-scalar/max-cycles 100 integer #f 100 30 ("Max cycles for scalar systems: ~a")) 
            (amg/max-cycles 100 integer #f 100 30) 
            (wd-phi/amg-alpha 0.0001 real #f 0.0001 0.1 ("AMG tolerances: ~a")) 
            (dynamesh/smooth/laplace/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (x-mom/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (y-mom/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (z-mom/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (pressure/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (pressure-coupled/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (temperature/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (p1/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (disco/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (enthalpy/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (species/amg-alpha (0.0001) real-list #f (0.0001) (0.1)) 
            (potential/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (dqmom-iem/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (uds/amg-alpha (0.0001) real-list #f (0.0001) (0.1)) 
            (hyb-init/amg-alpha (0.0001 0.0001) real-list #f (0.0001 0.0001) (0.1 0.1)) 
            (mp/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (granular-temperature/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (pb-disc/amg-alpha (0.0001) real-list #f (0.0001) (0.1)) 
            (pb-qmom/amg-alpha (0.0001) real-list #f (0.0001) (0.1)) 
            (pb-smm/amg-alpha (0.0001) real-list #f (0.0001) (0.1)) 
            (pb-dqmom/amg-alpha (0.0001) real-list #f (0.0001) (0.1)) 
            (iac/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (lsfun/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (w-swirl/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (nut/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (k/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (epsilon/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (v2/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (f/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (kl/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (omega/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (intermit/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (retheta/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (drsm/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (acoustics-waveeq/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (fmean/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (fmean2/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (fvar/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (fvar2/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (ic-fvar/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (vc-fvar/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (vd-fvar/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (ufla-y/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (premixc/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (pdftss/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (pull/amg-alpha 0.0001 real #f 0.0001 0.0001) 
            (amg-c/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (soot-mom/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (tvar/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (ignition/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (ecfm-sigma/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (premix-g-eqn/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (premix-g-var/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (inert/amg-alpha 0.0001 real #f 0.0001 0.1) 
            (wetsteam/amg-alpha 0.0001 real #f 0.0001 0.1)
        ) 
        ("default-urfs" 1000 
            (lambda () (rpgetvar 'solver/mode/default-urfs)) 
            (lambda () #t) 
            (pseudo-auto-time-step? #t boolean #f #t #t) 
            (pseudo-auto-time-solid? #t boolean #f #t #t) 
            (pseudo/autotime-lscale-option 1 integer #f 1 1) 
            (pseudo-auto-time-step-scale-factor 1. real #f 1. 1.) 
            (pressure-coupled/mom/pseudo-explicit-relax 0.5 real #f 0.5 0.5) 
            (pressure-coupled/pressure/pseudo-explicit-relax 0.5 real #f 0.5 0.5) 
            (potential/pseudo-relax 0.75 real #f 0.75 0.75) 
            (potential-faradaic/pseudo-relax 0.1 real #f 0.1 0.1) 
            (drift/pseudo-relax 0.1 real #f 0.1 0.1) 
            (delh/pseudo-relax 0.9 real #f 0.9 0.9) 
            (disco/pseudo-relax 1. real #f 1. 1.) 
            (cvt/pseudo-relax 1. real #f 1. 1.) 
            (wd-phi/pseudo-relax 0.75 real #f 0.75 0.75) 
            (dynamesh/smooth/laplace/pseudo-relax 0.75 real #f 0.75 0.75) 
            (mom/pseudo-relax 0.5 real #f 0.5 0.5) 
            (pressure/pseudo-relax 0.5 real #f 0.5 0.5) 
            (temperature/pseudo-relax 0.75 real #f 0.75 0.75) 
            (tvar/pseudo-relax 0.75 real #f 0.75 0.75) 
            (enthalpy/pseudo-relax 0.75 real #f 0.75 0.75) 
            (species/pseudo-relax (0.75) real-list #f (0.75) (0.75)) 
            (dqmom-iem/pseudo-relax 0.75 real #f 0.75 0.75) 
            (mp/pseudo-relax 0.5 real #f 0.5 0.5) 
            (w-swirl/pseudo-relax 0.75 real #f 0.75 0.75) 
            (nut/pseudo-relax 0.75 real #f 0.75 0.75) 
            (k/pseudo-relax 0.75 real #f 0.75 0.75) 
            (epsilon/pseudo-relax 0.75 real #f 0.75 0.75) 
            (v2/pseudo-relax 0.75 real #f 0.75 0.75) 
            (f/pseudo-relax 0.75 real #f 0.75 0.75) 
            (kl/pseudo-relax 0.75 real #f 0.75 0.75) 
            (omega/pseudo-relax 0.75 real #f 0.75 0.75) 
            (intermit/pseudo-relax 0.75 real #f 0.75 0.75) 
            (retheta/pseudo-relax 0.75 real #f 0.75 0.75) 
            (drsm/pseudo-relax 0.75 real #f 0.75 0.75) 
            (fmean/pseudo-relax 0.75 real #f 0.75 0.75) 
            (fmean2/pseudo-relax 0.75 real #f 0.75 0.75) 
            (fvar/pseudo-relax 0.75 real #f 0.75 0.75) 
            (fvar2/pseudo-relax 0.75 real #f 0.75 0.75) 
            (premixc/pseudo-relax 0.75 real #f 0.75 0.75) 
            (pdftss/pseudo-relax 0.75 real #f 0.75 0.75) 
            (pull/pseudo-relax 0.75 real #f 0.75 0.75) 
            (granular-temperature/pseudo-relax 0.75 real #f 0.75 0.75) 
            (ecfm-sigma/pseudo-relax 0.75 real #f 0.75 0.75) 
            (premix-g-var/pseudo-relax 0.75 real #f 0.75 0.75) 
            (inert/pseudo-relax 0.75 real #f 0.75 0.75) 
            (pollutant/pseudo-relax (0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75) real-list #f (0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75) (0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75)) 
            (pb-qmom/pseudo-relax (0.75) real-list #f (0.75) (0.75)) 
            (pb-smm/pseudo-relax (0.75) real-list #f (0.75) (0.75)) 
            (pb-dqmom/pseudo-relax (0.75) real-list #f (0.75) (0.75)) 
            (pb-disc/pseudo-relax (0.75) real-list #f (0.75) (0.75)) 
            (iac/pseudo-relax 0.75 real #f 0.75 0.75) 
            (wetsteam/pseudo-relax 0.75 real #f 0.75 0.6) 
            (density/pseudo-relax 1. real #f 1. 1.) 
            (body-force/pseudo-relax 1. real #f 1. 1.) 
            (turb-viscosity/pseudo-relax 1. real #f 1. 1.) 
            (p1/pseudo-relax 1. real #f 1. 1.) 
            (soot-mom/pseudo-relax 1. real #f 1. 0.75) 
            (uds/pseudo-relax (0.75) real-list #f (0.75) (0.75)) 
            (potential/pseudo-implicit-relax 1. real #f 1. 1.) 
            (temperature/pseudo-implicit-relax 1. real #f 1. 1.) 
            (tvar/pseudo-implicit-relax 0.9 real #f 0.9 0.9) 
            (enthalpy/pseudo-implicit-relax 1. real #f 1. 1.) 
            (species/pseudo-implicit-relax (1.) real-list #f (1.) (1.)) 
            (dqmom-iem/pseudo-implicit-relax 1. real #f 1. 1.) 
            (mp/pseudo-implicit-relax 0.5 real #f 0.5 0.5) 
            (w-swirl/pseudo-implicit-relax 0.9 real #f 0.9 0.9) 
            (nut/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (k/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (epsilon/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (v2/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (f/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (kl/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (omega/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (intermit/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (retheta/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (drsm/pseudo-implicit-relax 0.5 real #f 0.5 0.5) 
            (fmean/pseudo-implicit-relax 1. real #f 1. 1.) 
            (fmean2/pseudo-implicit-relax 1. real #f 1. 1.) 
            (fvar/pseudo-implicit-relax 0.9 real #f 0.9 0.9) 
            (fvar2/pseudo-implicit-relax 0.9 real #f 0.9 0.9) 
            (premixc/pseudo-implicit-relax 0.9 real #f 0.9 0.9) 
            (pdftss/pseudo-implicit-relax 1. real #f 1. 1.) 
            (granular-temperature/pseudo-implicit-relax 0.2 real #f 0.2 0.2) 
            (ecfm-sigma/pseudo-implicit-relax 0.9 real #f 0.9 0.9) 
            (premix-g-var/pseudo-implicit-relax 0.8 real #f 0.8 0.8) 
            (inert/pseudo-implicit-relax 1. real #f 1. 1.) 
            (pollutant/pseudo-implicit-relax (1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.) real-list #f (1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.) (1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.)) 
            (pb-qmom/pseudo-implicit-relax (0.5) real-list #f (0.5) (0.5)) 
            (pb-smm/pseudo-implicit-relax (0.5) real-list #f (0.5) (0.5)) 
            (pb-dqmom/pseudo-implicit-relax (0.5) real-list #f (0.5) (0.5)) 
            (pb-disc/pseudo-implicit-relax (0.5) real-list #f (0.5) (0.5)) 
            (iac/pseudo-implicit-relax 0.3 real #f 0.3 0.3) 
            (wetsteam/pseudo-implicit-relax 0.1 real #f 0.1 0.1) 
            (soot-mom/pseudo-implicit-relax 1. real #f 1. 1.) 
            (sootspecies/pseudo-implicit-relax 1. real #f 1. 1.) 
            (uds/pseudo-implicit-relax (1.) real-list #f (1.) (1.)) 
            (potential/pseudo-specific? #f boolean #f #f #f) 
            (temperature/pseudo-specific? #t boolean #f #t #t) 
            (tvar/pseudo-specific? #f boolean #f #f #f) 
            (enthalpy/pseudo-specific? #f boolean #f #f #f) 
            (species/pseudo-specific? (#f) boolean-list #f (#f) (#f)) 
            (dqmom-iem/pseudo-specific? #f boolean #f #f #f) 
            (mp/pseudo-specific? #t boolean #f #t #t) 
            (w-swirl/pseudo-specific? #t boolean #f #t #t) 
            (nut/pseudo-specific? #t boolean #f #t #t) 
            (k/pseudo-specific? #t boolean #f #t #t) 
            (epsilon/pseudo-specific? #t boolean #f #t #t) 
            (v2/pseudo-specific? #t boolean #f #t #t) 
            (f/pseudo-specific? #t boolean #f #t #t) 
            (kl/pseudo-specific? #t boolean #f #t #t) 
            (omega/pseudo-specific? #t boolean #f #t #t) 
            (intermit/pseudo-specific? #t boolean #f #t #t) 
            (retheta/pseudo-specific? #t boolean #f #t #t) 
            (drsm/pseudo-specific? #t boolean #f #t #t) 
            (fmean/pseudo-specific? #f boolean #f #f #f) 
            (fmean2/pseudo-specific? #f boolean #f #f #f) 
            (fvar/pseudo-specific? #f boolean #f #f #f) 
            (fvar2/pseudo-specific? #f boolean #f #f #f) 
            (premixc/pseudo-specific? #f boolean #f #f #f) 
            (pdftss/pseudo-specific? #f boolean #f #f #f) 
            (granular-temperature/pseudo-specific? #t boolean #f #t #t) 
            (ecfm-sigma/pseudo-specific? #f boolean #f #f #f) 
            (premix-g-var/pseudo-specific? #f boolean #f #f #f) 
            (inert/pseudo-specific? #f boolean #f #f #f) 
            (pollutant/pseudo-specific? (#f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f) boolean-list #f (#f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f) (#f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f)) 
            (pb-qmom/pseudo-specific? (#t) boolean-list #f (#t) (#t)) 
            (pb-smm/pseudo-specific? (#t) boolean-list #f (#t) (#t)) 
            (pb-dqmom/pseudo-specific? (#t) boolean-list #f (#t) (#t)) 
            (pb-disc/pseudo-specific? (#t) boolean-list #f (#t) (#t)) 
            (iac/pseudo-specific? #t boolean #f #t #t) 
            (wetsteam/pseudo-specific? #t boolean #f #t #t) 
            (soot-mom/pseudo-specific? #f boolean #f #f #f) 
            (uds/pseudo-specific? (#f) boolean-list #f (#f) (#f)) 
            (mom/update-derivatives-after-flow-solve? #t boolean #f #t #t)
        ) 
        ("overset-solver-defaults" 1004 
            (lambda () (and (rpgetvar 'solver/mode/overset-defaults?) (sg-overset?))) 
            (lambda () #f) 
            (amg/divergence-epsilon 1000000. real #f 1000000. 1000.) 
            (amg/laplace-coarsening? #f boolean #f #f #f) 
            (amg-coupled/laplace-coarsening? #f boolean #f #f #f)
        ) 
        ("vof-filling" 1004 
            (lambda () (rpgetvar 'solver/mode/vof-filling)) 
            (lambda () #f) 
            (residuals/scale? #f boolean #f #f #t) 
            (residuals/normalize? #t boolean () #t #f) 
            (residuals/n-maximize-norms 1 integer #f 1 5) 
            (residuals/convergence-criterion-type 1 integer () 1 0) 
            (pressure/ho-rc-disable? #t boolean #f #t #f) 
            (pressure/unsteady? #f boolean #f #f #t) 
            (pressure/presto-unsteady 0 integer #f 0 1) 
            (models/equation-order 1 integer #f 1 0) 
            (pressure/relax 0.7 real #f 0.7 0.3) 
            (mom/relax 0.7 real #f 0.7 0.7) 
            (mp/relax 0.7 real #f 0.7 0.5) 
            (pressure/scheme 18 integer #f 18 12) 
            (mom/scheme 0 integer #f 0 1) 
            (flow/scheme 21 integer #f 21 20) 
            (pressure/max-iter 0 integer #f 0 10) 
            (vof/node-based-unlimited-grad? #f boolean #f #f #t) 
            (recon/vof/limit? #f boolean #f #f #t) 
            (vof/node-based-deriv? #f boolean #f #f #t) 
            (vof/node-based-gradients? #f boolean #f #f #t)
         #f)
    )
)))
