(39 (94 fluid s-- 1)(
 (material . air)
 (sources? . #f)
 (source-terms (mass) (x-momentum) (y-momentum) (z-momentum) (k) (epsilon))
 (fixed? . #f)
 (cylindrical-fixed-var? . #f)
 (fixes (x-velocity (inactive . #f) (constant . 0) (profile "" "")) (y-velocity (inactive . #f) (constant . 0) (profile "" "")) (z-velocity (inactive . #f) (constant . 0) (profile "" "")) (k (inactive . #f) (constant . 0) (profile "" "")) (epsilon (inactive . #f) (constant . 0) (profile "" "")))
 (motion-spec . 0)
 (relative-to-thread . -1)
 (omega . 0)
 (grid-x-vel . 0)
 (grid-y-vel . 0)
 (grid-z-vel . 0)
 (x-origin . 0)
 (y-origin . 0)
 (z-origin . 0)
 (axis-origin-component 0 0 0)
 (ai . 0)
 (aj . 0)
 (ak . 1)
 (axis-direction-component 0 0 1)
 (udf-zmotion-name . "none")
 (mrf-motion? . #f)
 (mrf-relative-to-thread . -1)
 (mrf-omega (constant . 0) (profile "" ""))
 (mrf-grid-x-vel (constant . 0) (profile "" ""))
 (mrf-grid-y-vel (constant . 0) (profile "" ""))
 (mrf-grid-z-vel (constant . 0) (profile "" ""))
 (reference-frame-velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mrf-x-origin (constant . 0) (profile "" ""))
 (mrf-y-origin (constant . 0) (profile "" ""))
 (mrf-z-origin (constant . 0) (profile "" ""))
 (reference-frame-axis-origin-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mrf-ai (constant . 0) (profile "" ""))
 (mrf-aj (constant . 0) (profile "" ""))
 (mrf-ak (constant . 1) (profile "" ""))
 (reference-frame-axis-direction-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")))
 (mrf-udf-zmotion-name . "none")
 (mgrid-enable-transient? . #f)
 (mgrid-motion? . #f)
 (mgrid-relative-to-thread . -1)
 (mgrid-omega (constant . 0) (profile "" ""))
 (mgrid-grid-x-vel (constant . 0) (profile "" ""))
 (mgrid-grid-y-vel (constant . 0) (profile "" ""))
 (mgrid-grid-z-vel (constant . 0) (profile "" ""))
 (moving-mesh-velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mgrid-x-origin (constant . 0) (profile "" ""))
 (mgrid-y-origin (constant . 0) (profile "" ""))
 (mgrid-z-origin (constant . 0) (profile "" ""))
 (moving-mesh-axis-origin-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mgrid-ai (constant . 0) (profile "" ""))
 (mgrid-aj (constant . 0) (profile "" ""))
 (mgrid-ak (constant . 1) (profile "" ""))
 (moving-mesh-axis-direction-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")))
 (mgrid-udf-zmotion-name . "none")
 (solid-motion? . #f)
 (solid-relative-to-thread . -1)
 (solid-omega (constant . 0) (profile "" ""))
 (solid-grid-x-vel (constant . 0) (profile "" ""))
 (solid-grid-y-vel (constant . 0) (profile "" ""))
 (solid-grid-z-vel (constant . 0) (profile "" ""))
 (solid-motion-velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (solid-x-origin (constant . 0) (profile "" ""))
 (solid-y-origin (constant . 0) (profile "" ""))
 (solid-z-origin (constant . 0) (profile "" ""))
 (solid-motion-axis-origin-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (solid-ai (constant . 0) (profile "" ""))
 (solid-aj (constant . 0) (profile "" ""))
 (solid-ak (constant . 1) (profile "" ""))
 (solid-motion-axis-direction-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")))
 (solid-udf-zmotion-name . "none")
 (radiating? . #t)
 (deactivated? . #f)
 (les-embedded? . #f)
 (contact-property? . #f)
 (active-wetsteam-zone? . #t)
 (vapor-phase-realgas . -1)
 (laminar? . #f)
 (laminar-mut-zero? . #t)
 (les-embedded-spec . 1)
 (les-embedded-mom-scheme . 0)
 (les-embedded-c-wale . 0.3250000000000001)
 (les-embedded-c-smag . 0.1)
 (glass? . #f)
 (porous? . #f)
 (conical? . #f)
 (dir-spec-cond . 0)
 (cursys? . #f)
 (zonal-models? . #f)
 (zonal-flow? . #f)
 (zonal-flow-spec . 0)
 (zonal-pseudo-time-spec . 0)
 (zonal-time-advancement? . #f)
 (zonal-physical-dt-ratio . 1)
 (cursys-name . "Select Curvilinear Coordinate System...")
 (direction-1/x (constant . 1) (profile "" ""))
 (direction-1/y (constant . 0) (profile "" ""))
 (direction-1/z (constant . 0) (profile "" ""))
 (direction-1-components ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (direction-2/x (constant . 0) (profile "" ""))
 (direction-2/y (constant . 1) (profile "" ""))
 (direction-2/z (constant . 0) (profile "" ""))
 (direction-2-components ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")))
 (cone-axis/x . 1)
 (cone-axis/y . 0)
 (cone-axis/z . 0)
 (cone-axis-components 1 0 0)
 (cone-axis-pt/x . 1)
 (cone-axis-pt/y . 0)
 (cone-axis-pt/z . 0)
 (point-on-cone-axis-components 1 0 0)
 (cone-angle . 0)
 (rel-vel-resistance? . #t)
 (porous-r/1 (constant . 211100000) (profile "" ""))
 (porous-r/2 (constant . 211100000) (profile "" ""))
 (porous-r/3 (constant . 211100000) (profile "" ""))
 (viscous-resistance-components ((constant . 211100000) (profile "" "")) ((constant . 211100000) (profile "" "")) ((constant . 211100000) (profile "" "")))
 (alt-inertial-form? . #f)
 (porous-c/1 (constant . 0) (profile "" ""))
 (porous-c/2 (constant . 0) (profile "" ""))
 (porous-c/3 (constant . 0) (profile "" ""))
 (inertial-resistance-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (c0 . 0)
 (c1 . 0)
 (power-law-model-constants 0 0)
 (porosity (constant . 1) (profile "" ""))
 (viscosity-ratio (constant . 1.))
 (rad-porous-wall? . #f)
 (rad-porous-wall-in-emiss (constant . 1) (profile "" ""))
 (rad-porous-wall-diffuse-fraction . 1)
 (none? . #t)
 (corey? . #f)
 (stone-1? . #f)
 (stone-2? . #f)
 (rel-perm-limit-p1 . 1e-08)
 (rel-perm-limit-p2 . 1e-08)
 (ref-perm-p1 . 1.)
 (exp-p1 . 1.)
 (res-sat-p1 . 0.)
 (ref-perm-p2 . 1.)
 (exp-p2 . 1.)
 (res-sat-p2 . 0.)
 (ref-perm-p3 . 1.)
 (exp-p3 . 3.5)
 (res-sat-p3 . 0.05)
 (capillary-pressure (none . #f))
 (max-capillary-pressure . 10000000.)
 (van-genuchten-pg . 667.)
 (van-genuchten-ng . 2.8)
 (skjaeveland-nw-pc-coef . 900000.)
 (skjaeveland-nw-pc-pwr . 0.05)
 (skjaeveland-wet-pc-coef . 900000.)
 (skjaeveland-wet-pc-pwr . 0.05)
 (brooks-corey-pe . 440.)
 (brooks-corey-ng . 1.124)
 (leverett-con-ang . 0.3490658503988659)
 (rp-cbox-p1 . #f)
 (rp-edit-p1 . #f)
 (rel-perm-tabular-p1? . #f)
 (rel-perm-table-p1 . "none")
 (rel-perm-satw-p1 . "none")
 (rel-perm-rp-p1 . "none")
 (rp-cbox-p2 . #f)
 (rp-edit-p2 . #f)
 (rel-perm-tabular-p2? . #f)
 (rel-perm-table-p2 . "none")
 (rel-perm-satw-p2 . "none")
 (rel-perm-rp-p2 . "none")
 (wetting-phase . 2)
 (non-wetting-phase . 2)
 (equib-thermal? . #t)
 (non-equib-thermal? . #f)
 (solid-material . aluminum)
 (area-density (constant . 1) (profile "" ""))
 (heat-transfer-coeff (constant . 1) (profile "" ""))
 (fanzone? . #f)
 (fan-zone-list . 13)
 (fan-thickness . 0)
 (fan-hub-rad . 0)
 (fan-tip-rad . 0)
 (fan-x-origin . 0)
 (fan-y-origin . 0)
 (fan-z-origin . 0)
 (fan-origin-components 0 0 0)
 (fan-rot-dir . 0)
 (fan-opert-angvel . 0)
 (fan-inflection-point . 0.8300000000000001)
 (limit-flow-fan . #f)
 (max-flow-rate . 0)
 (min-flow-rate . 0)
 (tan-source-term . #f)
 (rad-source-term . #f)
 (axial-source-term . #f)
 (fan-axial-source-method . 0)
 (fan-pre-jump . 0)
 (fan-curve-fit . 0)
 (fan-poly-order . 0)
 (fan-ini-flow . 0)
 (fan-test-angvel . 0)
 (fan-test-temp . 0)
 (fan-curve-filename . "")
 (read-fan-curve . 65357928)
 (reaction-mechs . 0)
 (react? . #t)
 (surface-volume-ratio . 0)
 (faradaic-heat? . #f)
 (mp-compressive-beta-max . 2)
 (mp-boiling-zone? . #t)
 (numerical-beach? . #f)
 (beach-id . 1)
 (beach-multi-dir? . #f)
 (beach-damp-type . 0)
 (beach-inlet-bndr . 0)
 (beach-fs-level . 0)
 (beach-bottom-level . 0)
 (beach-dir-ni . 1)
 (beach-dir-nj . 0)
 (beach-dir-nk . 0)
 (beach-damp-len-spec . 0)
 (beach-wave-len . 0)
 (beach-len-factor . 2)
 (beach-start-point . 0)
 (beach-end-point . 0)
 (beach-dir-list ((ni . 1) (nj . 0) (nk . 0) (xe . 0) (len . 1)) ((ni . 1) (nj . 0) (nk . 0) (xe . 0) (len . 1)))
 (beach-damp-relative? . #t)
 (beach-damp-resist-lin . 10)
 (beach-damp-resist . 10)
 (porous-structure? . #f)
 (structure-material . aluminum)
 (anisotropic-spe-diff? . #f)
 (spe-diff-xx . 1)
 (spe-diff-xy . 0)
 (spe-diff-xz . 0)
 (spe-diff-yx . 0)
 (spe-diff-yy . 1)
 (spe-diff-yz . 0)
 (spe-diff-zx . 0)
 (spe-diff-zy . 0)
 (spe-diff-zz . 1)
 (wall-treatment? . #f)
))
(39 (12 velocity-inlet inlet 1)(
 (geom-disable? . #f)
 (geom-dir-spec . #f)
 (geom-dir-x . 0.)
 (geom-dir-y . 0.)
 (geom-dir-z . 0.)
 (geom-levels . 3)
 (geom-bgthread . 0)
 (system-coupling? . #f)
 (open-channel-wave-bc? . #f)
 (ocw-vel-segregated? . #f)
 (velocity-spec . 2)
 (frame-of-reference . 0)
 (vmag (constant . 0.1) (profile "" ""))
 (wave-velocity-spec . 1)
 (wave-vmag (constant . 0) (profile "" ""))
 (wave-u (constant . 0) (profile "" ""))
 (wave-v (constant . 0) (profile "" ""))
 (wave-w (constant . 0) (profile "" ""))
 (wave-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (ocw-ship-vel-spec . 1)
 (ocw-ship-vmag (constant . 0) (profile "" ""))
 (ocw-ship-ni (constant . 1) (profile "" ""))
 (ocw-ship-nj (constant . 0) (profile "" ""))
 (ocw-ship-nk (constant . 0) (profile "" ""))
 (moving-object-direction-components ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (ocw-sp-vel-spec . 1)
 (ocw-sp-vmag (constant . 0) (profile "" ""))
 (ocw-sp-ni (constant . 1) (profile "" ""))
 (ocw-sp-nj (constant . 0) (profile "" ""))
 (ocw-sp-nk (constant . 0) (profile "" ""))
 (secondary-phase-direction-components ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (ocw-pp-vel-spec . 1)
 (ocw-pp-ref-ht . 10.)
 (ocw-pp-power-coeff . 0.16)
 (ocw-pp-vmag (constant . 0) (profile "" ""))
 (ocw-pp-vmag-ref (constant . 0) (profile "" ""))
 (ocw-pp-ni (constant . 1) (profile "" ""))
 (ocw-pp-nj (constant . 0) (profile "" ""))
 (ocw-pp-nk (constant . 0) (profile "" ""))
 (primary-phase-direction-components ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (p_sup (constant . 0) (profile "" ""))
 (coordinate-system . 0)
 (u (constant . 0) (profile "" ""))
 (v (constant . 0) (profile "" ""))
 (w (constant . 0) (profile "" ""))
 (velocity-component ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (ni (constant . 1) (profile "" ""))
 (nj (constant . 0) (profile "" ""))
 (nk (constant . 0) (profile "" ""))
 (flow-direction-component ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (ai . 1)
 (aj . 0)
 (ak . 0)
 (axis-direction-component 1 0 0)
 (x-origin . 0)
 (y-origin . 0)
 (z-origin . 0)
 (axis-origin-component 0 0 0)
 (omega-swirl . 0)
 (phase-spec . 0)
 (wave-bc-type . 0)
 (ht-local (constant . 0) (profile "" ""))
 (ht-bottom (constant . -100) (profile "" ""))
 (wave-dir-spec . 0)
 (wave-ni (constant . 1) (profile "" ""))
 (wave-nj (constant . 0) (profile "" ""))
 (wave-nk (constant . 0) (profile "" ""))
 (reference-direction ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (wave-modeling-type . 0)
 (wave-list ((theory . 0) (wave-ht (constant . 1.) (profile "" "")) (wave-len (constant . 1.) (profile "" "")) (phase-diff (constant . 0) (profile "" "")) (heading-angle (constant . 0) (profile "" ""))))
 (wave-list-shallow ((theory . 0) (wave-ht (constant . 1.) (profile "" "")) (wave-len (constant . 1.) (profile "" "")) (offset (constant . 0) (profile "" "")) (heading-angle (constant . 0) (profile "" ""))))
 (wave-spect-method-freq . 0)
 (wave-spect-factor . 3.3)
 (wave-spect-sig-wave-ht (constant . 1.) (profile "" ""))
 (wave-spect-peak-freq (constant . 0.5) (profile "" ""))
 (wave-spect-min-freq (constant . 0.25) (profile "" ""))
 (wave-spect-max-freq (constant . 1.25) (profile "" ""))
 (wave-spect-freq-components . 50)
 (wave-spect-method-dir . 0)
 (wave-spect-s . 1)
 (wave-spect-mean-angle (constant . 0) (profile "" ""))
 (wave-spect-deviation (constant . 1.570796326794897) (profile "" ""))
 (wave-spect-dir-components . 4)
 (t (constant . 300) (profile "" ""))
 (non-equil-boundary? . #f)
 (tve (constant . 300) (profile "" ""))
 (les-spec-name . "No Perturbations")
 (rfg-number-of-modes . 250)
 (vm-number-of-vortices . 190)
 (vm-streamwise-fluct? . #t)
 (vm-mass-conservation? . #f)
 (stg-scale-limiter-type . 0)
 (stg-ti-limiter . 2.)
 (stg-tvr-limiter . 10.)
 (stg-dw-limiter . 0.)
 (volumetric-synthetic-turbulence-generator? . #f)
 (volumetric-synthetic-turbulence-generator-option . 0)
 (volumetric-synthetic-turbulence-generator-option-thickness . 0.)
 (ke-spec . 3)
 (nut (constant . 0.0001) (profile "" ""))
 (kl (constant . 1e-06) (profile "" ""))
 (intermit (constant . 1) (profile "" ""))
 (k (constant . 1) (profile "" ""))
 (e (constant . 1) (profile "" ""))
 (o (constant . 1) (profile "" ""))
 (v2 (constant . 1) (profile "" ""))
 (turb-intensity . 0.01)
 (turb-length-scale . 1)
 (turb-hydraulic-diam . 0.06)
 (turb-viscosity-ratio . 10)
 (turb-viscosity-ratio-profile (constant . 10) (profile "" ""))
 (rst-spec . 0)
 (uu (constant . 1) (profile "" ""))
 (vv (constant . 1) (profile "" ""))
 (ww (constant . 1) (profile "" ""))
 (uv (constant . 0) (profile "" ""))
 (vw (constant . 0) (profile "" ""))
 (uw (constant . 0) (profile "" ""))
 (ksgs-spec . 0)
 (ksgs (constant . 1) (profile "" ""))
 (sgs-turb-intensity . 0.1)
 (granular-temperature (constant . 0.0001) (profile "" ""))
 (iac (constant . 0.0001) (profile "" ""))
 (lsfun (constant . 0.) (profile "" ""))
 (volume-fraction (constant . 0) (profile "" ""))
 (species-in-mole-fractions? . #f)
 (mf ((constant . 0) (profile "" "")))
 (mole-fraction ((constant . 0) (profile "" "")))
 (elec-potential-type . 0)
 (elec-potential-value (constant . 0) (profile "" ""))
 (dual-potential-type . 0)
 (dual-potential-value (constant . 0) (profile "" ""))
 (x-displacement-type . 0)
 (x-displacement-value (constant . 0) (profile "" ""))
 (y-displacement-type . 0)
 (y-displacement-value (constant . 0) (profile "" ""))
 (z-displacement-type . 0)
 (z-displacement-value (constant . 0) (profile "" ""))
 (prob-mode-1 (constant . 0) (profile "" ""))
 (prob-mode-2 (constant . 0) (profile "" ""))
 (prob-mode-3 (constant . 0) (profile "" ""))
 (equ-required? . #f)
 (uds-bc)
 (uds)
 (pb-disc-bc)
 (pb-disc)
 (pb-qmom-bc)
 (pb-qmom)
 (pb-qbmm-bc)
 (pb-qbmm)
 (pb-smm-bc)
 (pb-smm)
 (pb-dqmom-bc)
 (pb-dqmom)
 (p (constant . 0) (profile "" ""))
 (premixc (constant . 0) (profile "" ""))
 (premixc-var (constant . 0) (profile "" ""))
 (ecfm-sigma (constant . 0) (profile "" ""))
 (inert (constant . 0) (profile "" ""))
 (pollut_no (constant . 0) (profile "" ""))
 (pollut_hcn (constant . 0) (profile "" ""))
 (pollut_nh3 (constant . 0) (profile "" ""))
 (pollut_n2o (constant . 0) (profile "" ""))
 (pollut_urea (constant . 0) (profile "" ""))
 (pollut_hnco (constant . 0) (profile "" ""))
 (pollut_nco (constant . 0) (profile "" ""))
 (pollut_so2 (constant . 0) (profile "" ""))
 (pollut_h2s (constant . 0) (profile "" ""))
 (pollut_so3 (constant . 0) (profile "" ""))
 (pollut_sh (constant . 0) (profile "" ""))
 (pollut_so (constant . 0) (profile "" ""))
 (pollut_soot (constant . 0) (profile "" ""))
 (pollut_nuclei (constant . 0) (profile "" ""))
 (pollut_ctar (constant . 0) (profile "" ""))
 (pollut_hg (constant . 0) (profile "" ""))
 (pollut_hgcl2 (constant . 0) (profile "" ""))
 (pollut_hcl (constant . 0) (profile "" ""))
 (pollut_hgo (constant . 0) (profile "" ""))
 (pollut_cl (constant . 0) (profile "" ""))
 (pollut_cl2 (constant . 0) (profile "" ""))
 (pollut_hgcl (constant . 0) (profile "" ""))
 (pollut_hocl (constant . 0) (profile "" ""))
 (radiation-bc . 3)
 (q-ni (constant . 1) (profile "" ""))
 (q-nj (constant . 0) (profile "" ""))
 (q-nk (constant . 0) (profile "" ""))
 (radial-direction-component ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (coll-dtheta . 1.744e-08)
 (coll-dphi . 1.744e-08)
 (band-q-irrad ((constant . 0) (profile "" "")))
 (band-q-irrad-diffuse ((constant . 0) (profile "" "")))
 (parallel-collimated-beam? . #t)
 (solar-direction? . #f)
 (solar-irradiation? . #f)
 (t-b-b-spec . 0)
 (t-b-b . 300)
 (in-emiss (constant . 1) (profile "" ""))
 (fmean (constant . 0) (profile "" ""))
 (fvar (constant . 0) (profile "" ""))
 (fmean2 (constant . 0) (profile "" ""))
 (fvar2 (constant . 0) (profile "" ""))
 (tss-scalar ((constant . 0) (profile "" "")))
 (dpm/bc-type . 4)
 (dpm/bc-collision-partner . "*dem-unknown*")
 (dpm-reinj-inj . "*pick-an-injection*")
 (dpm/bc-udf . "none")
 (fensapice/flow/bc-subtype . 0)
 (fensapice/drop/bccustom? . #f)
 (fensapice/drop/lwc . 0.001)
 (fensapice/drop/dtemp . 288)
 (fensapice/drop/ddiam . 20)
 (fensapice/drop/dv? . #f)
 (fensapice/drop/dx . 0.)
 (fensapice/drop/dy . 0.)
 (fensapice/drop/dz . 0.)
 (fensapice/dpm/surface-injection? . #f)
 (fensapice/dpm/inj-nstream . 1000000)
 (fensapice/dpm/rh-mode . 0)
 (fensapice/drop/icc . 0.008999999999999999)
 (fensapice/drop/ctemp . 288)
 (fensapice/drop/cmelt . 1)
 (fensapice/drop/cdiam . 100)
 (fensapice/drop/cv? . #f)
 (fensapice/drop/cx . 0)
 (fensapice/drop/cy . 0)
 (fensapice/drop/cz . 0)
 (fensapice/drop/vrh? . #t)
 (fensapice/drop/vrh . 100)
 (fensapice/drop/vc . 0.04)
 (mixing-plane-thread? . #f)
 (solar-fluxes? . #t)
 (solar-shining-factor . 1)
 (radiating-s2s-surface? . #t)
 (ac-options . 0)
 (impedance-0 . 0)
 (impedance-1)
 (impedance-2)
 (ac-wave (constant . 0) (profile "" ""))
 (les-spec . 0)
))
(39 (14 pressure-outlet outlet 1)(
 (geom-disable? . #f)
 (geom-dir-spec . #f)
 (geom-dir-x . 0.)
 (geom-dir-y . 0.)
 (geom-dir-z . 0.)
 (geom-levels . 3)
 (geom-bgthread . 0)
 (system-coupling? . #f)
 (open-channel? . #f)
 (outlet-number . 1)
 (press-spec-gen . 0)
 (press-spec . 0)
 (frame-of-reference . 0)
 (phase-spec . 0)
 (ht-local (constant . 0) (profile "" ""))
 (p (constant . 0) (profile "" ""))
 (p-profile-multiplier . 1)
 (ht-bottom (constant . -100) (profile "" ""))
 (den-spec . 0)
 (t0 (constant . 300) (profile "" ""))
 (direction-spec . 1)
 (coordinate-system . 0)
 (ni (constant . 1) (profile "" ""))
 (nj (constant . 0) (profile "" ""))
 (nk (constant . 0) (profile "" ""))
 (flow-direction-component ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (ai . 1)
 (aj . 0)
 (ak . 0)
 (x-origin . 0)
 (y-origin . 0)
 (z-origin . 0)
 (axis-direction-component 1 0 0)
 (axis-origin-component 0 0 0)
 (ke-spec . 3)
 (nut (constant . 0.0001) (profile "" ""))
 (kl (constant . 1e-06) (profile "" ""))
 (intermit (constant . 1) (profile "" ""))
 (k (constant . 1) (profile "" ""))
 (e (constant . 1) (profile "" ""))
 (o (constant . 1) (profile "" ""))
 (v2 (constant . 1) (profile "" ""))
 (turb-intensity . 0.01)
 (turb-length-scale . 1)
 (turb-hydraulic-diam . 0.06)
 (turb-viscosity-ratio . 10)
 (turb-viscosity-ratio-profile (constant . 10) (profile "" ""))
 (rst-spec . 0)
 (uu (constant . 1) (profile "" ""))
 (vv (constant . 1) (profile "" ""))
 (ww (constant . 1) (profile "" ""))
 (uv (constant . 0) (profile "" ""))
 (vw (constant . 0) (profile "" ""))
 (uw (constant . 0) (profile "" ""))
 (ksgs-spec . 0)
 (ksgs (constant . 1) (profile "" ""))
 (sgs-turb-intensity . 0.1)
 (radiation-bc . 3)
 (q-ni (constant . 1) (profile "" ""))
 (q-nj (constant . 0) (profile "" ""))
 (q-nk (constant . 0) (profile "" ""))
 (radial-direction-component ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (coll-dtheta . 1.744e-08)
 (coll-dphi . 1.744e-08)
 (band-q-irrad ((constant . 0) (profile "" "")))
 (band-q-irrad-diffuse ((constant . 0) (profile "" "")))
 (parallel-collimated-beam? . #t)
 (solar-direction? . #f)
 (solar-irradiation? . #f)
 (t-b-b-spec . 0)
 (t-b-b . 300)
 (in-emiss (constant . 1) (profile "" ""))
 (fmean (constant . 0) (profile "" ""))
 (fmean2 (constant . 0) (profile "" ""))
 (fvar (constant . 0) (profile "" ""))
 (fvar2 (constant . 0) (profile "" ""))
 (granular-temperature (constant . 0.0001) (profile "" ""))
 (iac (constant . 0.0001) (profile "" ""))
 (lsfun (constant . 0.) (profile "" ""))
 (vof-spec . 0)
 (volume-fraction (constant . 0) (profile "" ""))
 (species-in-mole-fractions? . #f)
 (mf ((constant . 0) (profile "" "")))
 (mole-fraction ((constant . 0) (profile "" "")))
 (elec-potential-type . 0)
 (elec-potential-value (constant . 0) (profile "" ""))
 (dual-potential-type . 0)
 (dual-potential-value (constant . 0) (profile "" ""))
 (x-displacement-type . 0)
 (x-displacement-value (constant . 0) (profile "" ""))
 (y-displacement-type . 0)
 (y-displacement-value (constant . 0) (profile "" ""))
 (z-displacement-type . 0)
 (z-displacement-value (constant . 0) (profile "" ""))
 (prob-mode-1 (constant . 0) (profile "" ""))
 (prob-mode-2 (constant . 0) (profile "" ""))
 (prob-mode-3 (constant . 0) (profile "" ""))
 (premixc (constant . 0) (profile "" ""))
 (premixc-var (constant . 0) (profile "" ""))
 (ecfm-sigma (constant . 0) (profile "" ""))
 (inert (constant . 0) (profile "" ""))
 (pollut_no (constant . 0) (profile "" ""))
 (pollut_hcn (constant . 0) (profile "" ""))
 (pollut_nh3 (constant . 0) (profile "" ""))
 (pollut_n2o (constant . 0) (profile "" ""))
 (pollut_urea (constant . 0) (profile "" ""))
 (pollut_hnco (constant . 0) (profile "" ""))
 (pollut_nco (constant . 0) (profile "" ""))
 (pollut_so2 (constant . 0) (profile "" ""))
 (pollut_h2s (constant . 0) (profile "" ""))
 (pollut_so3 (constant . 0) (profile "" ""))
 (pollut_sh (constant . 0) (profile "" ""))
 (pollut_so (constant . 0) (profile "" ""))
 (pollut_soot (constant . 0) (profile "" ""))
 (pollut_nuclei (constant . 0) (profile "" ""))
 (pollut_ctar (constant . 0) (profile "" ""))
 (pollut_hg (constant . 0) (profile "" ""))
 (pollut_hgcl2 (constant . 0) (profile "" ""))
 (pollut_hcl (constant . 0) (profile "" ""))
 (pollut_hgo (constant . 0) (profile "" ""))
 (pollut_cl (constant . 0) (profile "" ""))
 (pollut_cl2 (constant . 0) (profile "" ""))
 (pollut_hgcl (constant . 0) (profile "" ""))
 (pollut_hocl (constant . 0) (profile "" ""))
 (tss-scalar ((constant . 0) (profile "" "")))
 (fensapice/flow/bc-subtype . 0)
 (fensapice/dpm/outlet-condition . 0)
 (fensapice/dpm/rh-mode . 0)
 (fensapice/drop/vrh . 100)
 (fensapice/drop/vc . 0.04)
 (uds-bc)
 (uds)
 (pb-disc-bc)
 (pb-disc)
 (pb-qmom-bc)
 (pb-qmom)
 (pb-qbmm-bc)
 (pb-qbmm)
 (pb-smm-bc)
 (pb-smm)
 (pb-dqmom-bc)
 (pb-dqmom)
 (dpm/bc-type . 4)
 (dpm/bc-collision-partner . "*dem-unknown*")
 (dpm-reinj-inj . "*pick-an-injection*")
 (dpm/bc-udf . "none")
 (mixing-plane-thread? . #f)
 (ac-options . 0)
 (p-backflow-spec . 0)
 (p-backflow-spec-gen . 0)
 (impedance-0 . 0)
 (impedance-1)
 (impedance-2)
 (ac-wave (constant . 0) (profile "" ""))
 (prevent-reverse-flow? . #f)
 (radial? . #f)
 (radial-ref-position . 0)
 (radial-specified-radius . 0)
 (radial-specified-span . 0.5)
 (avg-press-spec? . #f)
 (avg-option . 0)
 (targeted-mf-boundary? . #f)
 (targeted-mf (constant . 1) (profile "" ""))
 (targeted-mf-pmax (constant . 5000000) (profile "" ""))
 (targeted-mf-pmin (constant . 1) (profile "" ""))
 (gen-nrbc-spec . 0)
 (wsf (constant . 0) (profile "" ""))
 (wsb (constant . 0) (profile "" ""))
 (wsn (constant . 0) (profile "" ""))
 (solar-fluxes? . #t)
 (solar-shining-factor . 1)
 (radiating-s2s-surface? . #t)
))
(39 (13 wall wall 1)(
 (geom-disable? . #f)
 (geom-dir-spec . #f)
 (geom-dir-x . 0.)
 (geom-dir-y . 0.)
 (geom-dir-z . 0.)
 (geom-levels . 3)
 (geom-bgthread . 0)
 (d-constant . 0)
 (d (constant . 0) (profile "" ""))
 (q-dot (constant . 0) (profile "" ""))
 (material . aluminum)
 (thermal-bc . 1)
 (t (constant . 300) (profile "" ""))
 (q (constant . 0) (profile "" ""))
 (h (constant . 0) (profile "" ""))
 (tinf (constant . 300) (profile "" ""))
 (planar-conduction? . #f)
 (shell-conduction ((thickness . 0) (material . aluminum) (qdot (constant . 0) (profile))))
 (thin-wall ((thickness (constant . 0) (profile "" "")) (material . "aluminum") (qdot (constant . 0) ((profile "" "")))))
 (motion-bc . 0)
 (shear-bc . 0)
 (rough-bc . 0)
 (moving? . #f)
 (relative? . #t)
 (rotating? . #f)
 (vmag . 0)
 (ni . 1)
 (nj . 0)
 (nk . 0)
 (wall-translation-vector 1 0 0)
 (components? . #f)
 (api-motion-spec . "")
 (u (constant . 0) (profile "" ""))
 (v (constant . 0) (profile "" ""))
 (w (constant . 0) (profile "" ""))
 (velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (in-emiss (constant . 1) (profile "" ""))
 (ex-emiss (constant . 1) (profile "" ""))
 (trad (constant . 300) (profile "" ""))
 (int-rad? . #f)
 (trad-internal . 300)
 (area-enhancement-factor (constant . 1) (profile "" ""))
 (rough-option? . #t)
 (rough-nasa? . #f)
 (rough-shin-et-al? . #f)
 (rough-data? . #f)
 (api-sand-grain-rough-spec . "")
 (roughness-height (constant . 0) (profile "" ""))
 (roughness-const (constant . 0.5) (profile "" ""))
 (roughness-height-cp (constant . 0) (profile "" ""))
 (roughness-const-cp (constant . 0.5) (profile "" ""))
 (roughness-const-nasa (constant . 0.5) (profile "" ""))
 (roughness-const-shin (constant . 0.5) (profile "" ""))
 (roughness-const-data (constant . 0.5) (profile "" ""))
 (variable-roughness (inactive . #f) (profile "" ""))
 (free-stream-velocity . 1.)
 (free-stream-temp . 300.)
 (characteristic-length . 1.)
 (free-stream-temp-cp . 300.)
 (characteristic-length-cp . 1.)
 (liquid-content (constant . 1) (profile "" ""))
 (liquid-content-cp (constant . 1) (profile "" ""))
 (droplet-diameter (constant . 20) (profile "" ""))
 (dpm/bc-type . 2)
 (dpm/bc-collision-partner . "*dem-unknown*")
 (dpm-reinj-inj . "*pick-an-injection*")
 (dpm/bc-norm-coeff (polynomial angle 1))
 (dpm/bc-tang-coeff (polynomial angle 1))
 (dpm/bc-frictn-coeff (constant . 0.2) (polynomial piecewise-linear relative-velocity (0. . 0.5) (1. . 0.2) (10. . 0.2) (210. . 0.12)) (polynomial piecewise-polynomial relative-velocity (0. 1. 0.5 -0.6 0.3) (1. 10. 0.2) (10. 210. 0.196 -0.0004)))
 (dpm/bc-udf . "none")
 (dpm/film-splash-nsamp . 4)
 (dpm/crit-temp-option . 0)
 (dpm/crit-temp-factor . 1.)
 (dpm/calibratable-temp . 180.)
 (dpm/imping-splash-model . 0)
 (dpm/t-deposition-offset . 207.)
 (dpm/t-delta . 40.)
 (dpm/a-wet . 600.)
 (dpm/partial-evap-ratio . 0.08)
 (dpm/ra-roughness . 0.)
 (dpm/rz-roughness . 0.)
 (dpm/rq-roughness . 0.)
 (dpm/rsm-roughness . 0.)
 (dpm/bc-erosion-generic? . #t)
 (dpm/bc-erosion (polynomial angle 1))
 (dpm/bc-erosion-c (polynomial diameter 1.8e-09))
 (dpm/bc-erosion-n (polynomial normal-velocity 0))
 (dpm/bc-erosion-finnie? . #t)
 (dpm/bc-erosion-finnie-k . 2.12e-07)
 (dpm/bc-erosion-finnie-vel-exp . 2.)
 (dpm/bc-erosion-finnie-max-erosion-angle . 0.3228859)
 (dpm/bc-erosion-mclaury? . #t)
 (dpm/bc-erosion-mclaury-a . 1.99e-07)
 (dpm/bc-erosion-mclaury-vel-exp . 1.73)
 (dpm/bc-erosion-mclaury-transition-angle . 0.2617994)
 (dpm/bc-erosion-mclaury-b . -13.3)
 (dpm/bc-erosion-mclaury-c . 7.85)
 (dpm/bc-erosion-mclaury-w . 1.)
 (dpm/bc-erosion-mclaury-x . 1.09)
 (dpm/bc-erosion-mclaury-y . 0.125)
 (dpm/bc-erosion-oka? . #t)
 (dpm/bc-erosion-oka-e90 . 0.0006154)
 (dpm/bc-erosion-oka-hv . 1.8)
 (dpm/bc-erosion-oka-n1 . 0.8)
 (dpm/bc-erosion-oka-n2 . 1.3)
 (dpm/bc-erosion-oka-k2 . 2.35)
 (dpm/bc-erosion-oka-k3 . 0.19)
 (dpm/bc-erosion-oka-dref . 0.000326)
 (dpm/bc-erosion-oka-vref . 104.)
 (dpm/bc-erosion-dnv? . #t)
 (dpm/bc-erosion-dnv-k . 2e-09)
 (dpm/bc-erosion-dnv-n . 2.6)
 (dpm/bc-erosion-dnv-ductile? . #t)
 (dpm/bc-erosion-shear? . #t)
 (dpm/bc-erosion-shear-v . 1.89e-08)
 (dpm/bc-erosion-shear-c . 1.41)
 (dpm/bc-erosion-shear-packing-limit . 0.63)
 (dpm/bc-erosion-shielding? . #t)
 (dpm/wall-heat-exchange? . #f)
 (dpm/film-condensation? . #f)
 (dpm/film-bl-model? . #t)
 (dpm/film-stripping? . #f)
 (dpm/crit-stripping-const . 0.01)
 (dpm/film-separation-model . 1)
 (dpm/critical-we-number . 0)
 (dpm/film-separation-angle . 90)
 (dpm/allow-lwf-to-vof? . #t)
 (dpm/allow-vof-to-lwf? . #t)
 (dpm/initialize-lwf? . #f)
 (dpm/initial-height . 0.0001)
 (film-velocity 0 0 0)
 (dpm/initial-x-velocity . 0)
 (dpm/initial-y-velocity . 0)
 (dpm/initial-z-velocity . 0)
 (dpm/initial-temperature . 298.15)
 (dpm/initial-injection . "unspecified")
 (dpm/film-parcel-density . 1000000)
 (dpm/minimum-number-of-parcels . 1)
 (dpm/do-patch-lwf-now . #f)
 (dpm/in-situ-data-reduction? . #f)
 (dpm/data-redu/time-first-execution . 0.)
 (dpm/data-redu/time-interval . 1.)
 (dpm/data-redu/target-num-pcls-per-face . 10)
 (dpm/data-redu/velocity-intervals . 5)
 (dpm/data-redu/temperature-intervals . 5)
 (band-in-emiss ((constant . 1) (profile "" "")))
 (radiation-bc . 3)
 (mc-bsource-p? . #f)
 (mc-poldfun-p? . #f)
 (polar-func-type . "Expression")
 (mc-polar-expr (expression . "") (constant . 0))
 (read-polar-dist-func-from-file? . #f)
 (polar-pair-list ((polar-real-angle . 0) (polar-real-intensity . 0)) ((polar-real-angle . 0) (polar-real-intensity . 0)))
 (write-polar-dist-func-to-file? . #f)
 (pold-pair-list-rad . #f)
 (q-ni (constant . 1) (profile "" ""))
 (q-nj (constant . 0) (profile "" ""))
 (q-nk (constant . 0) (profile "" ""))
 (component-of-radiation-direction ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (coll-dtheta . 1.744e-08)
 (coll-dphi . 1.744e-08)
 (band-q-irrad ((constant . 0) (profile "" "")))
 (band-q-irrad-diffuse ((constant . 0) (profile "" "")))
 (band-diffuse-frac 1)
 (radiating-s2s-surface? . #t)
 (critical-zone? . #f)
 (fpsc . 1)
 (parallel-collimated-beam? . #t)
 (solar-fluxes? . #t)
 (solar-direction? . #f)
 (solar-irradiation? . #f)
 (v-transmissivity (constant . 0.8) (profile "" ""))
 (ir-transmissivity (constant . 0.8) (profile "" ""))
 (v-opq-absorbtivity (constant . 0.8) (profile "" ""))
 (ir-opq-absorbtivity (constant . 0.8) (profile "" ""))
 (v-st-absorbtivity (constant . 0.1) (profile "" ""))
 (ir-st-absorbtivity (constant . 0.1) (profile "" ""))
 (d-st-absorbtivity (constant . 0.1) (profile "" ""))
 (d-transmissivity (constant . 0.8) (profile "" ""))
 (fsi-interface? . #f)
 (react? . #f)
 (partially-catalytic? . #f)
 (partially-catalytic-material . 0)
 (partially-catalytic-recombination-coefficient-o (constant . 0.) (profile "" ""))
 (partially-catalytic-recombination-coefficient-n (constant . 0.) (profile "" ""))
 (partially-catalytic-recombination-model . 0)
 (species-spec 0)
 (mf ((constant . 0) (profile "" "")))
 (elec-potential-type . 0)
 (elec-potential-value (constant . 0) (profile "" ""))
 (elec-potential-jump (constant . 0) (profile "" ""))
 (elec-potential-resistance (constant . 0) (profile "" ""))
 (dual-potential-type . 0)
 (dual-potential-value (constant . 0) (profile "" ""))
 (echem-reaction? . #f)
 (elec-potential-mechs . 0)
 (faradaic-heat? . #f)
 (li-ion-type . 0)
 (li-ion-value (constant . 0) (profile "" ""))
 (x-displacement-type . 0)
 (x-displacement-value (constant . 0) (profile "" ""))
 (y-displacement-type . 0)
 (y-displacement-value (constant . 0) (profile "" ""))
 (z-displacement-type . 0)
 (z-displacement-value (constant . 0) (profile "" ""))
 (per-dispx (constant . 0) (profile "" ""))
 (per-dispy (constant . 0) (profile "" ""))
 (per-dispz (constant . 0) (profile "" ""))
 (periodic-displacement-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (per-imagx (constant . 0) (profile "" ""))
 (per-imagy (constant . 0) (profile "" ""))
 (per-imagz (constant . 0) (profile "" ""))
 (periodic-imaginary-displacement-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (freq (constant . 0) (profile "" ""))
 (amp (constant . 0) (profile "" ""))
 (nodal-diam . 0)
 (pass-number (constant . 0) (profile "" ""))
 (fwd? . #f)
 (aero? . #f)
 (cmplx? . #f)
 (norm? . #f)
 (method? . 0)
 (force-realx (constant . 0) (profile "" ""))
 (force-realy (constant . 0) (profile "" ""))
 (force-realz (constant . 0) (profile "" ""))
 (force-real-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (force-imagx (constant . 0) (profile "" ""))
 (force-imagy (constant . 0) (profile "" ""))
 (force-imagz (constant . 0) (profile "" ""))
 (force-imaginary-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (force-cmplx? . #f)
 (force-norm? . #f)
 (uds-bc 0)
 (uds . value)
 (gtemp-bc . 0)
 (g-temperature (constant . 1e-08) (profile "" ""))
 (g-qflux (constant . 0.) (profile "" ""))
 (wall-restitution-coeff . 0.2)
 (omega . 0)
 (x-origin . 0)
 (y-origin . 0)
 (z-origin . 0)
 (position-of-rotation-axis 0 0 0)
 (ai . 0)
 (aj . 0)
 (ak . 1)
 (direction-component-of-rotation-axis 0 0 1)
 (adhesion-angle)
 (specified-shear? . #f)
 (shear-x (constant . 0) (profile "" ""))
 (shear-y (constant . 0) (profile "" ""))
 (shear-z (constant . 0) (profile "" ""))
 (shear-stress-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (fslip . 0)
 (eslip . 0)
 (surf-tens-grad . 0.)
 (contact-resistance (constant . 0) (profile "" ""))
 (reaction-mechs . 0)
 (surf-washcoat-factor . 1)
 (initial-deposition-height . 0)
 (solid-species-density . 1)
 (ablation-select-model . "None")
 (ablation/vielle/a . 0.1)
 (ablation/vielle/n . 0.1)
 (ablation/flux? . #f)
 (ablation/surfacerxn/density . 0)
 (ablation/species-mf ((constant . 0) (profile "" "")))
 (specular-coeff . 0)
 (mom-accom-coef . 1)
 (therm-accom-coef . 1)
 (eve-accom-coef . 0.001)
 (film-wall? . #f)
 (film-wall-bc . 0)
 (film-height (constant . 0.) (profile "" ""))
 (film-u (constant . 0) (profile "" ""))
 (film-v (constant . 0) (profile "" ""))
 (film-w (constant . 0) (profile "" ""))
 (flux-momentum-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (film-relative-vel? . #f)
 (film-bc-imp-press? . #f)
 (film-temperature (constant . 300.) (profile "" ""))
 (film-scalar (constant . 0.) (profile "" ""))
 (film-source? . #f)
 (film-h-src (constant . 0.) (profile "" ""))
 (film-u-src (constant . 0.) (profile "" ""))
 (film-v-src (constant . 0.) (profile "" ""))
 (film-w-src (constant . 0.) (profile "" ""))
 (momentum-source-components ((constant . 0.) (profile "" "")) ((constant . 0.) (profile "" "")) ((constant . 0.) (profile "" "")))
 (film-t-src (constant . 0.) (profile "" ""))
 (film-s-src (constant . 0.) (profile "" ""))
 (film-phase-change? . #f)
 (film-phase-change-model . 1)
 (film-cond-const . 5.)
 (film-vapo-const . 20.)
 (film-cond-rate (constant . 0.) (profile "" ""))
 (film-vapo-rate (constant . 0.) (profile "" ""))
 (film-momentum-coupling? . #f)
 (film-splash-wall? . #f)
 (film-boundary-separation? . #f)
 (film-impinge-model . 0)
 (film-splash-nparc . 4)
 (film-crit-temp-factor . 1.1)
 (film-roughness-ra . 0.)
 (film-roughness-rz . 0.)
 (film-t-deposition-offset . 207.)
 (film-t-delta . 40.)
 (film-a-wet . 600.)
 (film-partial-evap-ratio . 0.08)
 (film-contact-angle? . #f)
 (film-contact-angle-mean (constant . 0.785398) (profile "" ""))
 (film-contact-angle-rstd . 0.05)
 (film-contact-angle-beta . 1.)
 (film-vof-coupling-high? . #f)
 (film-vof-trans-high . 0.5)
 (film-vof-trans-high-relax . 0.5)
 (film-vof-coupling-low? . #f)
 (film-vof-trans-low . 0.)
 (film-vof-trans-low-relax . 0.5)
 (film-nec-deposition? . #f)
 (film-nec-dps-rate-model . 0)
 (film-nec-dps-rate-scale . 1.)
 (film-nec-dps-rate-user (constant . 0.) (profile "" ""))
 (caf (constant . 1) (profile "" ""))
 (thermal-stabilization? . #f)
 (scale-factor . 0)
 (stab-method . 1)
 (fensapice/flow/bc-subtype . 0)
 (fensapice/ice/icing-mode . 1)
 (fensapice/ice/hflux-mode . 0)
 (fensapice/ice/hflux-value . 0)
 (fensapice/ice/hflux-file . "")
 (fensapice/ice/wall-thickness . 0)
 (fensapice/ice/wall-internal-temperature . 0)
 (fensapice/ice/wall-conductivity . 0)
 (fensapice/ice/film-height (constant . 0.) (profile "" ""))
 (fensapice/drop/vwet? . #f)
 (fensapice/drop/reinj? . #f)
 (fensapice/dpm/wall-condition . 0)
 (fensapice/dpm/udf-wall-cond . "")
 (fensapice/dpm/bc-norm-coeff 1)
 (fensapice/dpm/bc-tang-coeff 1)
 (boundary-advection? . #f)
))
(39 (93 interior interior--s-- 1)(
 (is-not-a-rans-les-interface . #t)
))