// A script to test Untitled.Sexp.
// usage: dotnet test-sexp.cs
// You need .net 10 or later to run this.

#:package Untitled.Sexp@0.1.2

using Untitled.Sexp;

var test_string = """
(39 (94 fluid s-- 1)(
 (material . air)
 (sources? . #f)
 (source-terms (mass) (x-momentum) (y-momentum) (z-momentum) (k) (epsilon))
 (fixed? . #f)
 (cylindrical-fixed-var? . #f)
 (fixes (x-velocity (inactive . #f) (constant . 0) (profile "" "")) (y-velocity (inactive . #f) (constant . 0) (profile "" "")) (z-velocity (inactive . #f) (constant . 0) (profile "" "")) (k (inactive . #f) (constant . 0) (profile "" "")) (epsilon (inactive . #f) (constant . 0) (profile "" "")))
 (motion-spec . 0)
 (relative-to-thread . -1)
 (omega . 0)
 (grid-x-vel . 0)
 (grid-y-vel . 0)
 (grid-z-vel . 0)
 (x-origin . 0)
 (y-origin . 0)
 (z-origin . 0)
 (axis-origin-component 0 0 0)
 (ai . 0)
 (aj . 0)
 (ak . 1)
 (axis-direction-component 0 0 1)
 (udf-zmotion-name . "none")
 (mrf-motion? . #f)
 (mrf-relative-to-thread . -1)
 (mrf-omega (constant . 0) (profile "" ""))
 (mrf-grid-x-vel (constant . 0) (profile "" ""))
 (mrf-grid-y-vel (constant . 0) (profile "" ""))
 (mrf-grid-z-vel (constant . 0) (profile "" ""))
 (reference-frame-velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mrf-x-origin (constant . 0) (profile "" ""))
 (mrf-y-origin (constant . 0) (profile "" ""))
 (mrf-z-origin (constant . 0) (profile "" ""))
 (reference-frame-axis-origin-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mrf-ai (constant . 0) (profile "" ""))
 (mrf-aj (constant . 0) (profile "" ""))
 (mrf-ak (constant . 1) (profile "" ""))
 (reference-frame-axis-direction-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")))
 (mrf-udf-zmotion-name . "none")
 (mgrid-enable-transient? . #f)
 (mgrid-motion? . #f)
 (mgrid-relative-to-thread . -1)
 (mgrid-omega (constant . 0) (profile "" ""))
 (mgrid-grid-x-vel (constant . 0) (profile "" ""))
 (mgrid-grid-y-vel (constant . 0) (profile "" ""))
 (mgrid-grid-z-vel (constant . 0) (profile "" ""))
 (moving-mesh-velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mgrid-x-origin (constant . 0) (profile "" ""))
 (mgrid-y-origin (constant . 0) (profile "" ""))
 (mgrid-z-origin (constant . 0) (profile "" ""))
 (moving-mesh-axis-origin-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (mgrid-ai (constant . 0) (profile "" ""))
 (mgrid-aj (constant . 0) (profile "" ""))
 (mgrid-ak (constant . 1) (profile "" ""))
 (moving-mesh-axis-direction-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")))
 (mgrid-udf-zmotion-name . "none")
 (solid-motion? . #f)
 (solid-relative-to-thread . -1)
 (solid-omega (constant . 0) (profile "" ""))
 (solid-grid-x-vel (constant . 0) (profile "" ""))
 (solid-grid-y-vel (constant . 0) (profile "" ""))
 (solid-grid-z-vel (constant . 0) (profile "" ""))
 (solid-motion-velocity-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (solid-x-origin (constant . 0) (profile "" ""))
 (solid-y-origin (constant . 0) (profile "" ""))
 (solid-z-origin (constant . 0) (profile "" ""))
 (solid-motion-axis-origin-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (solid-ai (constant . 0) (profile "" ""))
 (solid-aj (constant . 0) (profile "" ""))
 (solid-ak (constant . 1) (profile "" ""))
 (solid-motion-axis-direction-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")))
 (solid-udf-zmotion-name . "none")
 (radiating? . #t)
 (deactivated? . #f)
 (les-embedded? . #f)
 (contact-property? . #f)
 (active-wetsteam-zone? . #t)
 (vapor-phase-realgas . -1)
 (laminar? . #f)
 (laminar-mut-zero? . #t)
 (les-embedded-spec . 1)
 (les-embedded-mom-scheme . 0)
 (les-embedded-c-wale . 0.3250000000000001)
 (les-embedded-c-smag . 0.1)
 (glass? . #f)
 (porous? . #f)
 (conical? . #f)
 (dir-spec-cond . 0)
 (cursys? . #f)
 (zonal-models? . #f)
 (zonal-flow? . #f)
 (zonal-flow-spec . 0)
 (zonal-pseudo-time-spec . 0)
 (zonal-time-advancement? . #f)
 (zonal-physical-dt-ratio . 1)
 (cursys-name . "Select Curvilinear Coordinate System...")
 (direction-1/x (constant . 1) (profile "" ""))
 (direction-1/y (constant . 0) (profile "" ""))
 (direction-1/z (constant . 0) (profile "" ""))
 (direction-1-components ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (direction-2/x (constant . 0) (profile "" ""))
 (direction-2/y (constant . 1) (profile "" ""))
 (direction-2/z (constant . 0) (profile "" ""))
 (direction-2-components ((constant . 0) (profile "" "")) ((constant . 1) (profile "" "")) ((constant . 0) (profile "" "")))
 (cone-axis/x . 1)
 (cone-axis/y . 0)
 (cone-axis/z . 0)
 (cone-axis-components 1 0 0)
 (cone-axis-pt/x . 1)
 (cone-axis-pt/y . 0)
 (cone-axis-pt/z . 0)
 (point-on-cone-axis-components 1 0 0)
 (cone-angle . 0)
 (rel-vel-resistance? . #t)
 (porous-r/1 (constant . 211100000) (profile "" ""))
 (porous-r/2 (constant . 211100000) (profile "" ""))
 (porous-r/3 (constant . 211100000) (profile "" ""))
 (viscous-resistance-components ((constant . 211100000) (profile "" "")) ((constant . 211100000) (profile "" "")) ((constant . 211100000) (profile "" "")))
 (alt-inertial-form? . #f)
 (porous-c/1 (constant . 0) (profile "" ""))
 (porous-c/2 (constant . 0) (profile "" ""))
 (porous-c/3 (constant . 0) (profile "" ""))
 (inertial-resistance-components ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")) ((constant . 0) (profile "" "")))
 (c0 . 0)
 (c1 . 0)
 (power-law-model-constants 0 0)
 (porosity (constant . 1) (profile "" ""))
 (viscosity-ratio (constant . 1.))
 (rad-porous-wall? . #f)
 (rad-porous-wall-in-emiss (constant . 1) (profile "" ""))
 (rad-porous-wall-diffuse-fraction . 1)
 (none? . #t)
 (corey? . #f)
 (stone-1? . #f)
 (stone-2? . #f)
 (rel-perm-limit-p1 . 1e-08)
 (rel-perm-limit-p2 . 1e-08)
 (ref-perm-p1 . 1.)
 (exp-p1 . 1.)
 (res-sat-p1 . 0.)
 (ref-perm-p2 . 1.)
 (exp-p2 . 1.)
 (res-sat-p2 . 0.)
 (ref-perm-p3 . 1.)
 (exp-p3 . 3.5)
 (res-sat-p3 . 0.05)
 (capillary-pressure (none . #f))
 (max-capillary-pressure . 10000000.)
 (van-genuchten-pg . 667.)
 (van-genuchten-ng . 2.8)
 (skjaeveland-nw-pc-coef . 900000.)
 (skjaeveland-nw-pc-pwr . 0.05)
 (skjaeveland-wet-pc-coef . 900000.)
 (skjaeveland-wet-pc-pwr . 0.05)
 (brooks-corey-pe . 440.)
 (brooks-corey-ng . 1.124)
 (leverett-con-ang . 0.3490658503988659)
 (rp-cbox-p1 . #f)
 (rp-edit-p1 . #f)
 (rel-perm-tabular-p1? . #f)
 (rel-perm-table-p1 . "none")
 (rel-perm-satw-p1 . "none")
 (rel-perm-rp-p1 . "none")
 (rp-cbox-p2 . #f)
 (rp-edit-p2 . #f)
 (rel-perm-tabular-p2? . #f)
 (rel-perm-table-p2 . "none")
 (rel-perm-satw-p2 . "none")
 (rel-perm-rp-p2 . "none")
 (wetting-phase . 2)
 (non-wetting-phase . 2)
 (equib-thermal? . #t)
 (non-equib-thermal? . #f)
 (solid-material . aluminum)
 (area-density (constant . 1) (profile "" ""))
 (heat-transfer-coeff (constant . 1) (profile "" ""))
 (fanzone? . #f)
 (fan-zone-list . 13)
 (fan-thickness . 0)
 (fan-hub-rad . 0)
 (fan-tip-rad . 0)
 (fan-x-origin . 0)
 (fan-y-origin . 0)
 (fan-z-origin . 0)
 (fan-origin-components 0 0 0)
 (fan-rot-dir . 0)
 (fan-opert-angvel . 0)
 (fan-inflection-point . 0.8300000000000001)
 (limit-flow-fan . #f)
 (max-flow-rate . 0)
 (min-flow-rate . 0)
 (tan-source-term . #f)
 (rad-source-term . #f)
 (axial-source-term . #f)
 (fan-axial-source-method . 0)
 (fan-pre-jump . 0)
 (fan-curve-fit . 0)
 (fan-poly-order . 0)
 (fan-ini-flow . 0)
 (fan-test-angvel . 0)
 (fan-test-temp . 0)
 (fan-curve-filename . "")
 (read-fan-curve . 65357928)
 (reaction-mechs . 0)
 (react? . #t)
 (surface-volume-ratio . 0)
 (faradaic-heat? . #f)
 (mp-compressive-beta-max . 2)
 (mp-boiling-zone? . #t)
 (numerical-beach? . #f)
 (beach-id . 1)
 (beach-multi-dir? . #f)
 (beach-damp-type . 0)
 (beach-inlet-bndr . 0)
 (beach-fs-level . 0)
 (beach-bottom-level . 0)
 (beach-dir-ni . 1)
 (beach-dir-nj . 0)
 (beach-dir-nk . 0)
 (beach-damp-len-spec . 0)
 (beach-wave-len . 0)
 (beach-len-factor . 2)
 (beach-start-point . 0)
 (beach-end-point . 0)
 (beach-dir-list ((ni . 1) (nj . 0) (nk . 0) (xe . 0) (len . 1)) ((ni . 1) (nj . 0) (nk . 0) (xe . 0) (len . 1)))
 (beach-damp-relative? . #t)
 (beach-damp-resist-lin . 10)
 (beach-damp-resist . 10)
 (porous-structure? . #f)
 (structure-material . aluminum)
 (anisotropic-spe-diff? . #f)
 (spe-diff-xx . 1)
 (spe-diff-xy . 0)
 (spe-diff-xz . 0)
 (spe-diff-yx . 0)
 (spe-diff-yy . 1)
 (spe-diff-yz . 0)
 (spe-diff-zx . 0)
 (spe-diff-zy . 0)
 (spe-diff-zz . 1)
 (wall-treatment? . #f)
))
""";

var values = Sexp.Parse(test_string);

var zone_data = values.AsPair().Cdr;
var properties = zone_data.AsPair().Cdr.AsPair().Car;

var valid_properties = new List<string>() { "sources", "sourceterms" };
foreach (var property in properties.AsEnumerable())
{
    string? key = null;
    string? value = null;

    if (property.IsList)
    {
        var lst = property.ToList();
        if (lst.Count >= 2)
        {
            key = lst[0].AsSymbol().Name.Replace("-", "").Replace("?", "").ToLower();
            if (!valid_properties.Contains(key))
                continue;
            if (key == "sourceterms")
            {
                var source_type = lst[1].AsPair().Car.ToString();
                var cdr_value = lst[1].AsPair().Cdr;
                if (cdr_value == SValue.Null) continue;
                var source_value = cdr_value.AsPair().Cdr.ToList();
                var source_profile = source_value[0].ToList();
                var profile_type = source_profile[1].AsString();
                var profile_name = source_profile[2].AsString();
                value = $"{source_type}-{profile_type}-{profile_name}";
            }
            else
            {
                value = lst[1].AsPair().Cdr.ToString();
            }
            Console.WriteLine("list");
            Console.WriteLine($"{key}: {value}");
        }
        else continue;
    }
    else if (property.IsPair)
    {
        var pair = property.AsPair();
        key = pair.Car.ToString().Replace("-", "").Replace("?", "").ToLower();
        if (!valid_properties.Contains(key))
            continue;
        value = pair.Cdr.ToString();
        Console.WriteLine("pair");
        Console.WriteLine($"{key}: {value}");
    }
}
